/********************************************************************************
** Form generated from reading UI file 'windowGUI.ui'
**
** Created by: Qt User Interface Compiler version 5.5.1
**
** WARNING! All changes made in this file will be lost when recompiling UI file!
********************************************************************************/

#ifndef UI_WINDOWGUI_H
#define UI_WINDOWGUI_H

#include <QtCore/QVariant>
#include <QtWidgets/QAction>
#include <QtWidgets/QApplication>
#include <QtWidgets/QButtonGroup>
#include <QtWidgets/QCheckBox>
#include <QtWidgets/QComboBox>
#include <QtWidgets/QFrame>
#include <QtWidgets/QHeaderView>
#include <QtWidgets/QLabel>
#include <QtWidgets/QLineEdit>
#include <QtWidgets/QMainWindow>
#include <QtWidgets/QMenuBar>
#include <QtWidgets/QPushButton>
#include <QtWidgets/QRadioButton>
#include <QtWidgets/QStatusBar>
#include <QtWidgets/QToolBar>
#include <QtWidgets/QWidget>
#include "glWidget.h"

QT_BEGIN_NAMESPACE

class Ui_windowGUI
{
public:
    QWidget *centralWidget;
    QLineEdit *disp_scaleGyro;
    QLineEdit *disp_scaleAccl;
    QLineEdit *disp_scaleMagn;
    QLineEdit *disp_scaleIMU;
    QCheckBox *disp_enableGyro;
    QCheckBox *disp_enableAccl;
    QFrame *line_v1;
    QCheckBox *disp_enableMagn;
    QCheckBox *disp_enableIMU;
    QLabel *label_display;
    QCheckBox *core_isGyro;
    QCheckBox *core_isAccl;
    QCheckBox *core_isMagn;
    QPushButton *view_up;
    QPushButton *view_side1;
    QPushButton *view_side2;
    QPushButton *select_reference;
    QPushButton *select_reset;
    QLineEdit *rect_gBias0;
    QLineEdit *rect_gBias1;
    QLineEdit *rect_gBias2;
    QLineEdit *rect_gMult1;
    QLineEdit *rect_gMult2;
    QLineEdit *rect_gMult0;
    QLineEdit *rect_gMult5;
    QLineEdit *rect_gMult3;
    QLineEdit *rect_gMult4;
    QLineEdit *rect_gMult8;
    QLineEdit *rect_gMult6;
    QLineEdit *rect_gMult7;
    QLabel *label_rect_gBias;
    QLabel *lable_rect_gMult;
    QLineEdit *rect_aBias1;
    QLineEdit *rect_aMult2;
    QLineEdit *rect_aMult7;
    QLineEdit *rect_aMult1;
    QLineEdit *rect_aMult0;
    QLineEdit *rect_aMult3;
    QLabel *label_rect_aMult;
    QLineEdit *rect_aMult8;
    QLineEdit *rect_aBias2;
    QLineEdit *rect_aBias0;
    QLineEdit *rect_aMult5;
    QLineEdit *rect_aMult6;
    QLabel *label_rect_aBias;
    QLineEdit *rect_aMult4;
    QLineEdit *rect_mBias1;
    QLineEdit *rect_mMult3;
    QLineEdit *rect_mMult2;
    QLineEdit *rect_mMult6;
    QLineEdit *rect_mMult1;
    QLabel *label_rect_mMult;
    QLineEdit *rect_mBias0;
    QLineEdit *rect_mMult0;
    QLineEdit *rect_mBias2;
    QLineEdit *rect_mMult4;
    QLabel *label_rect_mBias;
    QLineEdit *rect_mMult8;
    QLineEdit *rect_mMult5;
    QLineEdit *rect_mMult7;
    QFrame *line_h1;
    QLabel *label_core_gScale;
    QLabel *label_core;
    QFrame *calb_val;
    QLabel *label_stat_gBias;
    QLabel *label_stat_aMag;
    QLabel *label_stat_mMult;
    QLabel *label_stat_mDot;
    QLabel *text_aMag;
    QLabel *text_mMag;
    QLabel *text_mDot;
    QLabel *text_gBias;
    GLWidget *widget;
    QPushButton *rect_open;
    QPushButton *rect_save;
    QCheckBox *core_isPredict;
    QCheckBox *core_isFOM;
    QCheckBox *core_isTran;
    QLineEdit *core_gScale;
    QLineEdit *core_tranAlpha;
    QLabel *label_core_tranAlpha;
    QPushButton *core_save;
    QPushButton *core_open;
    QRadioButton *disp_vectRaw;
    QRadioButton *disp_vectCor;
    QRadioButton *disp_vectFltr;
    QLabel *label_core_aMagThresh;
    QLineEdit *core_aWeight;
    QLabel *label_core_aWeight;
    QLabel *label_core_aMag;
    QLineEdit *core_aMagThresh;
    QLineEdit *core_aMag;
    QLineEdit *core_mMag;
    QLabel *label_core_mWeight;
    QLabel *label_core_mMag;
    QLineEdit *core_mWeight;
    QLabel *label_core_mMagThresh;
    QLineEdit *core_mMagThresh;
    QLineEdit *core_mDot;
    QLabel *label_core_mDot;
    QLabel *label_core_mDotThresh;
    QLineEdit *core_mDotThresh;
    QFrame *line_h2;
    QFrame *line_v2;
    QCheckBox *pnts_isGyro;
    QCheckBox *pnts_isMagn;
    QCheckBox *pnts_isAccl;
    QLineEdit *pnts_tHold;
    QLabel *label_pnts_tHold;
    QLineEdit *pnts_tStable;
    QLabel *label_pnts_tStable;
    QLineEdit *pnts_gThresh;
    QLineEdit *pnts_gAlpha;
    QLabel *label_pnts_gAlpha;
    QLabel *label_pnts_gThresh;
    QLineEdit *pnts_aThresh;
    QLabel *label_pnts_aAlpha;
    QLineEdit *pnts_aAlpha;
    QLabel *label_pnts_aThresh;
    QLabel *label_pnts_mAlpha;
    QLineEdit *pnts_mAlpha;
    QLineEdit *pnts_mThresh;
    QLabel *label_pnts_mThresh;
    QPushButton *pnts_save;
    QPushButton *pnts_open;
    QComboBox *calb_type;
    QLineEdit *stat_alpha;
    QLabel *label_stat_alpha;
    QPushButton *stat_save;
    QPushButton *stat_open;
    QPushButton *calb_go;
    QLineEdit *pnts_val;
    QLabel *label_calb_val;
    QCheckBox *pnts_enable;
    QCheckBox *rect_enable;
    QCheckBox *stat_enable;
    QCheckBox *calb_enable;
    QPushButton *calb_save;
    QPushButton *calb_open;
    QLabel *text_state;
    QLabel *text_gBiasStd;
    QLabel *label_stat_gBiasStd;
    QLabel *label_stat_aMag_2;
    QLabel *text_aMagFOM;
    QLabel *label_stat_aMag_3;
    QLabel *text_aMagStd;
    QLabel *label_stat_mMult_2;
    QLabel *text_mMagFOM;
    QLabel *label_stat_mMult_3;
    QLabel *text_mMagStd;
    QLabel *text_mDotFOM;
    QLabel *label_stat_mDot_2;
    QLabel *text_mDotStd;
    QLabel *label_stat_mDot_3;
    QPushButton *stat_update;
    QMenuBar *menuBar;
    QToolBar *mainToolBar;
    QStatusBar *statusBar;
    QToolBar *toolBar;

    void setupUi(QMainWindow *windowGUI)
    {
        if (windowGUI->objectName().isEmpty())
            windowGUI->setObjectName(QStringLiteral("windowGUI"));
        windowGUI->resize(1400, 739);
        QFont font;
        font.setBold(false);
        font.setWeight(50);
        windowGUI->setFont(font);
        centralWidget = new QWidget(windowGUI);
        centralWidget->setObjectName(QStringLiteral("centralWidget"));
        disp_scaleGyro = new QLineEdit(centralWidget);
        disp_scaleGyro->setObjectName(QStringLiteral("disp_scaleGyro"));
        disp_scaleGyro->setGeometry(QRect(430, 40, 101, 27));
        disp_scaleAccl = new QLineEdit(centralWidget);
        disp_scaleAccl->setObjectName(QStringLiteral("disp_scaleAccl"));
        disp_scaleAccl->setGeometry(QRect(430, 80, 101, 27));
        disp_scaleMagn = new QLineEdit(centralWidget);
        disp_scaleMagn->setObjectName(QStringLiteral("disp_scaleMagn"));
        disp_scaleMagn->setGeometry(QRect(430, 120, 101, 27));
        disp_scaleIMU = new QLineEdit(centralWidget);
        disp_scaleIMU->setObjectName(QStringLiteral("disp_scaleIMU"));
        disp_scaleIMU->setGeometry(QRect(430, 160, 101, 27));
        disp_enableGyro = new QCheckBox(centralWidget);
        disp_enableGyro->setObjectName(QStringLiteral("disp_enableGyro"));
        disp_enableGyro->setGeometry(QRect(540, 40, 141, 22));
        disp_enableGyro->setChecked(false);
        disp_enableAccl = new QCheckBox(centralWidget);
        disp_enableAccl->setObjectName(QStringLiteral("disp_enableAccl"));
        disp_enableAccl->setGeometry(QRect(540, 80, 141, 22));
        disp_enableAccl->setChecked(false);
        line_v1 = new QFrame(centralWidget);
        line_v1->setObjectName(QStringLiteral("line_v1"));
        line_v1->setGeometry(QRect(710, 0, 20, 671));
        line_v1->setFrameShape(QFrame::VLine);
        line_v1->setFrameShadow(QFrame::Sunken);
        disp_enableMagn = new QCheckBox(centralWidget);
        disp_enableMagn->setObjectName(QStringLiteral("disp_enableMagn"));
        disp_enableMagn->setGeometry(QRect(540, 120, 141, 22));
        disp_enableMagn->setChecked(false);
        disp_enableIMU = new QCheckBox(centralWidget);
        disp_enableIMU->setObjectName(QStringLiteral("disp_enableIMU"));
        disp_enableIMU->setEnabled(true);
        disp_enableIMU->setGeometry(QRect(540, 160, 141, 22));
        disp_enableIMU->setChecked(true);
        label_display = new QLabel(centralWidget);
        label_display->setObjectName(QStringLiteral("label_display"));
        label_display->setGeometry(QRect(440, 0, 121, 17));
        QFont font1;
        font1.setPointSize(12);
        font1.setBold(true);
        font1.setWeight(75);
        label_display->setFont(font1);
        core_isGyro = new QCheckBox(centralWidget);
        core_isGyro->setObjectName(QStringLiteral("core_isGyro"));
        core_isGyro->setGeometry(QRect(730, 40, 97, 22));
        core_isAccl = new QCheckBox(centralWidget);
        core_isAccl->setObjectName(QStringLiteral("core_isAccl"));
        core_isAccl->setGeometry(QRect(830, 40, 97, 22));
        core_isMagn = new QCheckBox(centralWidget);
        core_isMagn->setObjectName(QStringLiteral("core_isMagn"));
        core_isMagn->setGeometry(QRect(940, 40, 97, 22));
        view_up = new QPushButton(centralWidget);
        view_up->setObjectName(QStringLiteral("view_up"));
        view_up->setGeometry(QRect(430, 240, 71, 27));
        view_side1 = new QPushButton(centralWidget);
        view_side1->setObjectName(QStringLiteral("view_side1"));
        view_side1->setGeometry(QRect(530, 240, 71, 27));
        view_side2 = new QPushButton(centralWidget);
        view_side2->setObjectName(QStringLiteral("view_side2"));
        view_side2->setGeometry(QRect(630, 240, 71, 27));
        select_reference = new QPushButton(centralWidget);
        select_reference->setObjectName(QStringLiteral("select_reference"));
        select_reference->setGeometry(QRect(440, 280, 111, 27));
        select_reset = new QPushButton(centralWidget);
        select_reset->setObjectName(QStringLiteral("select_reset"));
        select_reset->setGeometry(QRect(590, 280, 101, 27));
        rect_gBias0 = new QLineEdit(centralWidget);
        rect_gBias0->setObjectName(QStringLiteral("rect_gBias0"));
        rect_gBias0->setGeometry(QRect(1070, 60, 101, 27));
        rect_gBias1 = new QLineEdit(centralWidget);
        rect_gBias1->setObjectName(QStringLiteral("rect_gBias1"));
        rect_gBias1->setGeometry(QRect(1180, 60, 101, 27));
        rect_gBias2 = new QLineEdit(centralWidget);
        rect_gBias2->setObjectName(QStringLiteral("rect_gBias2"));
        rect_gBias2->setGeometry(QRect(1290, 60, 101, 27));
        rect_gMult1 = new QLineEdit(centralWidget);
        rect_gMult1->setObjectName(QStringLiteral("rect_gMult1"));
        rect_gMult1->setGeometry(QRect(1180, 120, 101, 27));
        rect_gMult2 = new QLineEdit(centralWidget);
        rect_gMult2->setObjectName(QStringLiteral("rect_gMult2"));
        rect_gMult2->setGeometry(QRect(1290, 120, 101, 27));
        rect_gMult0 = new QLineEdit(centralWidget);
        rect_gMult0->setObjectName(QStringLiteral("rect_gMult0"));
        rect_gMult0->setGeometry(QRect(1070, 120, 101, 27));
        rect_gMult5 = new QLineEdit(centralWidget);
        rect_gMult5->setObjectName(QStringLiteral("rect_gMult5"));
        rect_gMult5->setGeometry(QRect(1290, 150, 101, 27));
        rect_gMult3 = new QLineEdit(centralWidget);
        rect_gMult3->setObjectName(QStringLiteral("rect_gMult3"));
        rect_gMult3->setGeometry(QRect(1070, 150, 101, 27));
        rect_gMult4 = new QLineEdit(centralWidget);
        rect_gMult4->setObjectName(QStringLiteral("rect_gMult4"));
        rect_gMult4->setGeometry(QRect(1180, 150, 101, 27));
        rect_gMult8 = new QLineEdit(centralWidget);
        rect_gMult8->setObjectName(QStringLiteral("rect_gMult8"));
        rect_gMult8->setGeometry(QRect(1290, 180, 101, 27));
        rect_gMult6 = new QLineEdit(centralWidget);
        rect_gMult6->setObjectName(QStringLiteral("rect_gMult6"));
        rect_gMult6->setGeometry(QRect(1070, 180, 101, 27));
        rect_gMult7 = new QLineEdit(centralWidget);
        rect_gMult7->setObjectName(QStringLiteral("rect_gMult7"));
        rect_gMult7->setGeometry(QRect(1180, 180, 101, 27));
        label_rect_gBias = new QLabel(centralWidget);
        label_rect_gBias->setObjectName(QStringLiteral("label_rect_gBias"));
        label_rect_gBias->setGeometry(QRect(1170, 40, 121, 20));
        label_rect_gBias->setFont(font);
        lable_rect_gMult = new QLabel(centralWidget);
        lable_rect_gMult->setObjectName(QStringLiteral("lable_rect_gMult"));
        lable_rect_gMult->setGeometry(QRect(1110, 100, 231, 20));
        lable_rect_gMult->setFont(font);
        rect_aBias1 = new QLineEdit(centralWidget);
        rect_aBias1->setObjectName(QStringLiteral("rect_aBias1"));
        rect_aBias1->setGeometry(QRect(1180, 250, 101, 27));
        rect_aMult2 = new QLineEdit(centralWidget);
        rect_aMult2->setObjectName(QStringLiteral("rect_aMult2"));
        rect_aMult2->setGeometry(QRect(1290, 310, 101, 27));
        rect_aMult7 = new QLineEdit(centralWidget);
        rect_aMult7->setObjectName(QStringLiteral("rect_aMult7"));
        rect_aMult7->setGeometry(QRect(1180, 370, 101, 27));
        rect_aMult1 = new QLineEdit(centralWidget);
        rect_aMult1->setObjectName(QStringLiteral("rect_aMult1"));
        rect_aMult1->setGeometry(QRect(1180, 310, 101, 27));
        rect_aMult0 = new QLineEdit(centralWidget);
        rect_aMult0->setObjectName(QStringLiteral("rect_aMult0"));
        rect_aMult0->setGeometry(QRect(1070, 310, 101, 27));
        rect_aMult3 = new QLineEdit(centralWidget);
        rect_aMult3->setObjectName(QStringLiteral("rect_aMult3"));
        rect_aMult3->setGeometry(QRect(1070, 340, 101, 27));
        label_rect_aMult = new QLabel(centralWidget);
        label_rect_aMult->setObjectName(QStringLiteral("label_rect_aMult"));
        label_rect_aMult->setGeometry(QRect(1100, 290, 271, 20));
        label_rect_aMult->setFont(font);
        rect_aMult8 = new QLineEdit(centralWidget);
        rect_aMult8->setObjectName(QStringLiteral("rect_aMult8"));
        rect_aMult8->setGeometry(QRect(1290, 370, 101, 27));
        rect_aBias2 = new QLineEdit(centralWidget);
        rect_aBias2->setObjectName(QStringLiteral("rect_aBias2"));
        rect_aBias2->setGeometry(QRect(1290, 250, 101, 27));
        rect_aBias0 = new QLineEdit(centralWidget);
        rect_aBias0->setObjectName(QStringLiteral("rect_aBias0"));
        rect_aBias0->setGeometry(QRect(1070, 250, 101, 27));
        rect_aMult5 = new QLineEdit(centralWidget);
        rect_aMult5->setObjectName(QStringLiteral("rect_aMult5"));
        rect_aMult5->setGeometry(QRect(1290, 340, 101, 27));
        rect_aMult6 = new QLineEdit(centralWidget);
        rect_aMult6->setObjectName(QStringLiteral("rect_aMult6"));
        rect_aMult6->setGeometry(QRect(1070, 370, 101, 27));
        label_rect_aBias = new QLabel(centralWidget);
        label_rect_aBias->setObjectName(QStringLiteral("label_rect_aBias"));
        label_rect_aBias->setGeometry(QRect(1160, 230, 161, 20));
        label_rect_aBias->setFont(font);
        rect_aMult4 = new QLineEdit(centralWidget);
        rect_aMult4->setObjectName(QStringLiteral("rect_aMult4"));
        rect_aMult4->setGeometry(QRect(1180, 340, 101, 27));
        rect_mBias1 = new QLineEdit(centralWidget);
        rect_mBias1->setObjectName(QStringLiteral("rect_mBias1"));
        rect_mBias1->setGeometry(QRect(1180, 440, 101, 27));
        rect_mMult3 = new QLineEdit(centralWidget);
        rect_mMult3->setObjectName(QStringLiteral("rect_mMult3"));
        rect_mMult3->setGeometry(QRect(1070, 530, 101, 27));
        rect_mMult2 = new QLineEdit(centralWidget);
        rect_mMult2->setObjectName(QStringLiteral("rect_mMult2"));
        rect_mMult2->setGeometry(QRect(1290, 500, 101, 27));
        rect_mMult6 = new QLineEdit(centralWidget);
        rect_mMult6->setObjectName(QStringLiteral("rect_mMult6"));
        rect_mMult6->setGeometry(QRect(1070, 560, 101, 27));
        rect_mMult1 = new QLineEdit(centralWidget);
        rect_mMult1->setObjectName(QStringLiteral("rect_mMult1"));
        rect_mMult1->setGeometry(QRect(1180, 500, 101, 27));
        label_rect_mMult = new QLabel(centralWidget);
        label_rect_mMult->setObjectName(QStringLiteral("label_rect_mMult"));
        label_rect_mMult->setGeometry(QRect(1100, 480, 261, 20));
        label_rect_mMult->setFont(font);
        rect_mBias0 = new QLineEdit(centralWidget);
        rect_mBias0->setObjectName(QStringLiteral("rect_mBias0"));
        rect_mBias0->setGeometry(QRect(1070, 440, 101, 27));
        rect_mMult0 = new QLineEdit(centralWidget);
        rect_mMult0->setObjectName(QStringLiteral("rect_mMult0"));
        rect_mMult0->setGeometry(QRect(1070, 500, 101, 27));
        rect_mBias2 = new QLineEdit(centralWidget);
        rect_mBias2->setObjectName(QStringLiteral("rect_mBias2"));
        rect_mBias2->setGeometry(QRect(1290, 440, 101, 27));
        rect_mMult4 = new QLineEdit(centralWidget);
        rect_mMult4->setObjectName(QStringLiteral("rect_mMult4"));
        rect_mMult4->setGeometry(QRect(1180, 530, 101, 27));
        label_rect_mBias = new QLabel(centralWidget);
        label_rect_mBias->setObjectName(QStringLiteral("label_rect_mBias"));
        label_rect_mBias->setGeometry(QRect(1150, 420, 151, 20));
        label_rect_mBias->setFont(font);
        rect_mMult8 = new QLineEdit(centralWidget);
        rect_mMult8->setObjectName(QStringLiteral("rect_mMult8"));
        rect_mMult8->setGeometry(QRect(1290, 560, 101, 27));
        rect_mMult5 = new QLineEdit(centralWidget);
        rect_mMult5->setObjectName(QStringLiteral("rect_mMult5"));
        rect_mMult5->setGeometry(QRect(1290, 530, 101, 27));
        rect_mMult7 = new QLineEdit(centralWidget);
        rect_mMult7->setObjectName(QStringLiteral("rect_mMult7"));
        rect_mMult7->setGeometry(QRect(1180, 560, 101, 27));
        line_h1 = new QFrame(centralWidget);
        line_h1->setObjectName(QStringLiteral("line_h1"));
        line_h1->setGeometry(QRect(430, 310, 281, 20));
        line_h1->setFrameShape(QFrame::HLine);
        line_h1->setFrameShadow(QFrame::Sunken);
        label_core_gScale = new QLabel(centralWidget);
        label_core_gScale->setObjectName(QStringLiteral("label_core_gScale"));
        label_core_gScale->setGeometry(QRect(730, 120, 121, 20));
        label_core_gScale->setFont(font);
        label_core = new QLabel(centralWidget);
        label_core->setObjectName(QStringLiteral("label_core"));
        label_core->setGeometry(QRect(740, 0, 121, 20));
        label_core->setFont(font1);
        calb_val = new QFrame(centralWidget);
        calb_val->setObjectName(QStringLiteral("calb_val"));
        calb_val->setGeometry(QRect(1050, 0, 20, 671));
        calb_val->setFrameShape(QFrame::VLine);
        calb_val->setFrameShadow(QFrame::Sunken);
        label_stat_gBias = new QLabel(centralWidget);
        label_stat_gBias->setObjectName(QStringLiteral("label_stat_gBias"));
        label_stat_gBias->setGeometry(QRect(10, 460, 81, 20));
        label_stat_gBias->setFont(font);
        label_stat_aMag = new QLabel(centralWidget);
        label_stat_aMag->setObjectName(QStringLiteral("label_stat_aMag"));
        label_stat_aMag->setGeometry(QRect(10, 510, 81, 20));
        label_stat_aMag->setFont(font);
        label_stat_mMult = new QLabel(centralWidget);
        label_stat_mMult->setObjectName(QStringLiteral("label_stat_mMult"));
        label_stat_mMult->setGeometry(QRect(210, 460, 81, 20));
        label_stat_mMult->setFont(font);
        label_stat_mDot = new QLabel(centralWidget);
        label_stat_mDot->setObjectName(QStringLiteral("label_stat_mDot"));
        label_stat_mDot->setGeometry(QRect(210, 520, 81, 20));
        label_stat_mDot->setFont(font);
        text_aMag = new QLabel(centralWidget);
        text_aMag->setObjectName(QStringLiteral("text_aMag"));
        text_aMag->setGeometry(QRect(100, 510, 101, 20));
        text_aMag->setFont(font);
        text_mMag = new QLabel(centralWidget);
        text_mMag->setObjectName(QStringLiteral("text_mMag"));
        text_mMag->setGeometry(QRect(300, 460, 111, 20));
        text_mMag->setFont(font);
        text_mDot = new QLabel(centralWidget);
        text_mDot->setObjectName(QStringLiteral("text_mDot"));
        text_mDot->setGeometry(QRect(300, 520, 111, 20));
        text_mDot->setFont(font);
        text_gBias = new QLabel(centralWidget);
        text_gBias->setObjectName(QStringLiteral("text_gBias"));
        text_gBias->setGeometry(QRect(100, 460, 101, 20));
        text_gBias->setFont(font);
        widget = new GLWidget(centralWidget);
        widget->setObjectName(QStringLiteral("widget"));
        widget->setGeometry(QRect(10, 0, 411, 411));
        rect_open = new QPushButton(centralWidget);
        rect_open->setObjectName(QStringLiteral("rect_open"));
        rect_open->setGeometry(QRect(1130, 640, 81, 27));
        rect_save = new QPushButton(centralWidget);
        rect_save->setObjectName(QStringLiteral("rect_save"));
        rect_save->setGeometry(QRect(1250, 640, 81, 27));
        core_isPredict = new QCheckBox(centralWidget);
        core_isPredict->setObjectName(QStringLiteral("core_isPredict"));
        core_isPredict->setGeometry(QRect(940, 70, 97, 22));
        core_isFOM = new QCheckBox(centralWidget);
        core_isFOM->setObjectName(QStringLiteral("core_isFOM"));
        core_isFOM->setGeometry(QRect(730, 70, 97, 22));
        core_isTran = new QCheckBox(centralWidget);
        core_isTran->setObjectName(QStringLiteral("core_isTran"));
        core_isTran->setGeometry(QRect(830, 70, 111, 22));
        core_gScale = new QLineEdit(centralWidget);
        core_gScale->setObjectName(QStringLiteral("core_gScale"));
        core_gScale->setGeometry(QRect(730, 140, 151, 27));
        core_tranAlpha = new QLineEdit(centralWidget);
        core_tranAlpha->setObjectName(QStringLiteral("core_tranAlpha"));
        core_tranAlpha->setGeometry(QRect(900, 140, 151, 27));
        label_core_tranAlpha = new QLabel(centralWidget);
        label_core_tranAlpha->setObjectName(QStringLiteral("label_core_tranAlpha"));
        label_core_tranAlpha->setGeometry(QRect(900, 120, 121, 20));
        label_core_tranAlpha->setFont(font);
        core_save = new QPushButton(centralWidget);
        core_save->setObjectName(QStringLiteral("core_save"));
        core_save->setGeometry(QRect(910, 440, 81, 27));
        core_open = new QPushButton(centralWidget);
        core_open->setObjectName(QStringLiteral("core_open"));
        core_open->setGeometry(QRect(790, 440, 81, 27));
        disp_vectRaw = new QRadioButton(centralWidget);
        disp_vectRaw->setObjectName(QStringLiteral("disp_vectRaw"));
        disp_vectRaw->setGeometry(QRect(430, 200, 81, 22));
        disp_vectCor = new QRadioButton(centralWidget);
        disp_vectCor->setObjectName(QStringLiteral("disp_vectCor"));
        disp_vectCor->setGeometry(QRect(510, 200, 111, 22));
        disp_vectCor->setChecked(true);
        disp_vectFltr = new QRadioButton(centralWidget);
        disp_vectFltr->setObjectName(QStringLiteral("disp_vectFltr"));
        disp_vectFltr->setGeometry(QRect(620, 200, 81, 22));
        label_core_aMagThresh = new QLabel(centralWidget);
        label_core_aMagThresh->setObjectName(QStringLiteral("label_core_aMagThresh"));
        label_core_aMagThresh->setGeometry(QRect(950, 190, 91, 20));
        label_core_aMagThresh->setFont(font);
        core_aWeight = new QLineEdit(centralWidget);
        core_aWeight->setObjectName(QStringLiteral("core_aWeight"));
        core_aWeight->setGeometry(QRect(730, 210, 101, 27));
        label_core_aWeight = new QLabel(centralWidget);
        label_core_aWeight->setObjectName(QStringLiteral("label_core_aWeight"));
        label_core_aWeight->setGeometry(QRect(730, 190, 61, 20));
        label_core_aWeight->setFont(font);
        label_core_aMag = new QLabel(centralWidget);
        label_core_aMag->setObjectName(QStringLiteral("label_core_aMag"));
        label_core_aMag->setGeometry(QRect(840, 190, 71, 20));
        label_core_aMag->setFont(font);
        core_aMagThresh = new QLineEdit(centralWidget);
        core_aMagThresh->setObjectName(QStringLiteral("core_aMagThresh"));
        core_aMagThresh->setGeometry(QRect(950, 210, 101, 27));
        core_aMag = new QLineEdit(centralWidget);
        core_aMag->setObjectName(QStringLiteral("core_aMag"));
        core_aMag->setGeometry(QRect(840, 210, 101, 27));
        core_mMag = new QLineEdit(centralWidget);
        core_mMag->setObjectName(QStringLiteral("core_mMag"));
        core_mMag->setGeometry(QRect(840, 280, 101, 27));
        label_core_mWeight = new QLabel(centralWidget);
        label_core_mWeight->setObjectName(QStringLiteral("label_core_mWeight"));
        label_core_mWeight->setGeometry(QRect(730, 260, 61, 20));
        label_core_mWeight->setFont(font);
        label_core_mMag = new QLabel(centralWidget);
        label_core_mMag->setObjectName(QStringLiteral("label_core_mMag"));
        label_core_mMag->setGeometry(QRect(840, 260, 71, 20));
        label_core_mMag->setFont(font);
        core_mWeight = new QLineEdit(centralWidget);
        core_mWeight->setObjectName(QStringLiteral("core_mWeight"));
        core_mWeight->setGeometry(QRect(730, 280, 101, 27));
        label_core_mMagThresh = new QLabel(centralWidget);
        label_core_mMagThresh->setObjectName(QStringLiteral("label_core_mMagThresh"));
        label_core_mMagThresh->setGeometry(QRect(950, 260, 91, 20));
        label_core_mMagThresh->setFont(font);
        core_mMagThresh = new QLineEdit(centralWidget);
        core_mMagThresh->setObjectName(QStringLiteral("core_mMagThresh"));
        core_mMagThresh->setGeometry(QRect(950, 280, 101, 27));
        core_mDot = new QLineEdit(centralWidget);
        core_mDot->setObjectName(QStringLiteral("core_mDot"));
        core_mDot->setGeometry(QRect(840, 330, 101, 27));
        label_core_mDot = new QLabel(centralWidget);
        label_core_mDot->setObjectName(QStringLiteral("label_core_mDot"));
        label_core_mDot->setGeometry(QRect(840, 310, 71, 20));
        label_core_mDot->setFont(font);
        label_core_mDotThresh = new QLabel(centralWidget);
        label_core_mDotThresh->setObjectName(QStringLiteral("label_core_mDotThresh"));
        label_core_mDotThresh->setGeometry(QRect(950, 310, 91, 20));
        label_core_mDotThresh->setFont(font);
        core_mDotThresh = new QLineEdit(centralWidget);
        core_mDotThresh->setObjectName(QStringLiteral("core_mDotThresh"));
        core_mDotThresh->setGeometry(QRect(950, 330, 101, 27));
        line_h2 = new QFrame(centralWidget);
        line_h2->setObjectName(QStringLiteral("line_h2"));
        line_h2->setGeometry(QRect(730, 470, 321, 20));
        line_h2->setFrameShape(QFrame::HLine);
        line_h2->setFrameShadow(QFrame::Sunken);
        line_v2 = new QFrame(centralWidget);
        line_v2->setObjectName(QStringLiteral("line_v2"));
        line_v2->setGeometry(QRect(410, 420, 20, 251));
        line_v2->setFrameShape(QFrame::VLine);
        line_v2->setFrameShadow(QFrame::Sunken);
        pnts_isGyro = new QCheckBox(centralWidget);
        pnts_isGyro->setObjectName(QStringLiteral("pnts_isGyro"));
        pnts_isGyro->setGeometry(QRect(430, 380, 97, 22));
        pnts_isMagn = new QCheckBox(centralWidget);
        pnts_isMagn->setObjectName(QStringLiteral("pnts_isMagn"));
        pnts_isMagn->setGeometry(QRect(620, 380, 97, 22));
        pnts_isAccl = new QCheckBox(centralWidget);
        pnts_isAccl->setObjectName(QStringLiteral("pnts_isAccl"));
        pnts_isAccl->setGeometry(QRect(520, 380, 97, 22));
        pnts_tHold = new QLineEdit(centralWidget);
        pnts_tHold->setObjectName(QStringLiteral("pnts_tHold"));
        pnts_tHold->setGeometry(QRect(430, 440, 131, 27));
        label_pnts_tHold = new QLabel(centralWidget);
        label_pnts_tHold->setObjectName(QStringLiteral("label_pnts_tHold"));
        label_pnts_tHold->setGeometry(QRect(430, 420, 121, 20));
        label_pnts_tHold->setFont(font);
        pnts_tStable = new QLineEdit(centralWidget);
        pnts_tStable->setObjectName(QStringLiteral("pnts_tStable"));
        pnts_tStable->setGeometry(QRect(570, 440, 131, 27));
        label_pnts_tStable = new QLabel(centralWidget);
        label_pnts_tStable->setObjectName(QStringLiteral("label_pnts_tStable"));
        label_pnts_tStable->setGeometry(QRect(570, 420, 121, 20));
        label_pnts_tStable->setFont(font);
        pnts_gThresh = new QLineEdit(centralWidget);
        pnts_gThresh->setObjectName(QStringLiteral("pnts_gThresh"));
        pnts_gThresh->setGeometry(QRect(570, 490, 131, 27));
        pnts_gAlpha = new QLineEdit(centralWidget);
        pnts_gAlpha->setObjectName(QStringLiteral("pnts_gAlpha"));
        pnts_gAlpha->setGeometry(QRect(430, 490, 131, 27));
        label_pnts_gAlpha = new QLabel(centralWidget);
        label_pnts_gAlpha->setObjectName(QStringLiteral("label_pnts_gAlpha"));
        label_pnts_gAlpha->setGeometry(QRect(430, 470, 121, 20));
        label_pnts_gAlpha->setFont(font);
        label_pnts_gThresh = new QLabel(centralWidget);
        label_pnts_gThresh->setObjectName(QStringLiteral("label_pnts_gThresh"));
        label_pnts_gThresh->setGeometry(QRect(570, 470, 121, 20));
        label_pnts_gThresh->setFont(font);
        pnts_aThresh = new QLineEdit(centralWidget);
        pnts_aThresh->setObjectName(QStringLiteral("pnts_aThresh"));
        pnts_aThresh->setGeometry(QRect(570, 540, 131, 27));
        label_pnts_aAlpha = new QLabel(centralWidget);
        label_pnts_aAlpha->setObjectName(QStringLiteral("label_pnts_aAlpha"));
        label_pnts_aAlpha->setGeometry(QRect(430, 520, 121, 20));
        label_pnts_aAlpha->setFont(font);
        pnts_aAlpha = new QLineEdit(centralWidget);
        pnts_aAlpha->setObjectName(QStringLiteral("pnts_aAlpha"));
        pnts_aAlpha->setGeometry(QRect(430, 540, 131, 27));
        label_pnts_aThresh = new QLabel(centralWidget);
        label_pnts_aThresh->setObjectName(QStringLiteral("label_pnts_aThresh"));
        label_pnts_aThresh->setGeometry(QRect(570, 520, 121, 20));
        label_pnts_aThresh->setFont(font);
        label_pnts_mAlpha = new QLabel(centralWidget);
        label_pnts_mAlpha->setObjectName(QStringLiteral("label_pnts_mAlpha"));
        label_pnts_mAlpha->setGeometry(QRect(430, 570, 121, 20));
        label_pnts_mAlpha->setFont(font);
        pnts_mAlpha = new QLineEdit(centralWidget);
        pnts_mAlpha->setObjectName(QStringLiteral("pnts_mAlpha"));
        pnts_mAlpha->setGeometry(QRect(430, 590, 131, 27));
        pnts_mThresh = new QLineEdit(centralWidget);
        pnts_mThresh->setObjectName(QStringLiteral("pnts_mThresh"));
        pnts_mThresh->setGeometry(QRect(570, 590, 131, 27));
        label_pnts_mThresh = new QLabel(centralWidget);
        label_pnts_mThresh->setObjectName(QStringLiteral("label_pnts_mThresh"));
        label_pnts_mThresh->setGeometry(QRect(570, 570, 121, 20));
        label_pnts_mThresh->setFont(font);
        pnts_save = new QPushButton(centralWidget);
        pnts_save->setObjectName(QStringLiteral("pnts_save"));
        pnts_save->setGeometry(QRect(580, 640, 81, 27));
        pnts_open = new QPushButton(centralWidget);
        pnts_open->setObjectName(QStringLiteral("pnts_open"));
        pnts_open->setGeometry(QRect(470, 640, 81, 27));
        calb_type = new QComboBox(centralWidget);
        calb_type->setObjectName(QStringLiteral("calb_type"));
        calb_type->setGeometry(QRect(730, 550, 151, 27));
        stat_alpha = new QLineEdit(centralWidget);
        stat_alpha->setObjectName(QStringLiteral("stat_alpha"));
        stat_alpha->setGeometry(QRect(10, 640, 131, 27));
        label_stat_alpha = new QLabel(centralWidget);
        label_stat_alpha->setObjectName(QStringLiteral("label_stat_alpha"));
        label_stat_alpha->setGeometry(QRect(10, 620, 121, 20));
        label_stat_alpha->setFont(font);
        stat_save = new QPushButton(centralWidget);
        stat_save->setObjectName(QStringLiteral("stat_save"));
        stat_save->setGeometry(QRect(330, 640, 81, 27));
        stat_open = new QPushButton(centralWidget);
        stat_open->setObjectName(QStringLiteral("stat_open"));
        stat_open->setGeometry(QRect(240, 640, 81, 27));
        calb_go = new QPushButton(centralWidget);
        calb_go->setObjectName(QStringLiteral("calb_go"));
        calb_go->setGeometry(QRect(1000, 550, 51, 27));
        pnts_val = new QLineEdit(centralWidget);
        pnts_val->setObjectName(QStringLiteral("pnts_val"));
        pnts_val->setGeometry(QRect(890, 550, 101, 27));
        label_calb_val = new QLabel(centralWidget);
        label_calb_val->setObjectName(QStringLiteral("label_calb_val"));
        label_calb_val->setGeometry(QRect(890, 530, 71, 20));
        label_calb_val->setFont(font);
        pnts_enable = new QCheckBox(centralWidget);
        pnts_enable->setObjectName(QStringLiteral("pnts_enable"));
        pnts_enable->setGeometry(QRect(430, 340, 151, 22));
        pnts_enable->setFont(font1);
        rect_enable = new QCheckBox(centralWidget);
        rect_enable->setObjectName(QStringLiteral("rect_enable"));
        rect_enable->setGeometry(QRect(1070, 0, 151, 22));
        rect_enable->setFont(font1);
        stat_enable = new QCheckBox(centralWidget);
        stat_enable->setObjectName(QStringLiteral("stat_enable"));
        stat_enable->setGeometry(QRect(10, 420, 151, 22));
        stat_enable->setFont(font1);
        calb_enable = new QCheckBox(centralWidget);
        calb_enable->setObjectName(QStringLiteral("calb_enable"));
        calb_enable->setGeometry(QRect(730, 490, 201, 22));
        calb_enable->setFont(font1);
        calb_save = new QPushButton(centralWidget);
        calb_save->setObjectName(QStringLiteral("calb_save"));
        calb_save->setGeometry(QRect(910, 640, 81, 27));
        calb_open = new QPushButton(centralWidget);
        calb_open->setObjectName(QStringLiteral("calb_open"));
        calb_open->setGeometry(QRect(790, 640, 81, 27));
        text_state = new QLabel(centralWidget);
        text_state->setObjectName(QStringLiteral("text_state"));
        text_state->setGeometry(QRect(360, 412, 51, 20));
        text_state->setFont(font);
        text_state->setAutoFillBackground(true);
        text_state->setAlignment(Qt::AlignRight|Qt::AlignTrailing|Qt::AlignVCenter);
        text_gBiasStd = new QLabel(centralWidget);
        text_gBiasStd->setObjectName(QStringLiteral("text_gBiasStd"));
        text_gBiasStd->setGeometry(QRect(100, 480, 101, 20));
        text_gBiasStd->setFont(font);
        label_stat_gBiasStd = new QLabel(centralWidget);
        label_stat_gBiasStd->setObjectName(QStringLiteral("label_stat_gBiasStd"));
        label_stat_gBiasStd->setGeometry(QRect(10, 480, 81, 20));
        label_stat_gBiasStd->setFont(font);
        label_stat_aMag_2 = new QLabel(centralWidget);
        label_stat_aMag_2->setObjectName(QStringLiteral("label_stat_aMag_2"));
        label_stat_aMag_2->setGeometry(QRect(10, 530, 81, 20));
        label_stat_aMag_2->setFont(font);
        text_aMagFOM = new QLabel(centralWidget);
        text_aMagFOM->setObjectName(QStringLiteral("text_aMagFOM"));
        text_aMagFOM->setGeometry(QRect(100, 530, 101, 20));
        text_aMagFOM->setFont(font);
        label_stat_aMag_3 = new QLabel(centralWidget);
        label_stat_aMag_3->setObjectName(QStringLiteral("label_stat_aMag_3"));
        label_stat_aMag_3->setGeometry(QRect(10, 550, 81, 20));
        label_stat_aMag_3->setFont(font);
        text_aMagStd = new QLabel(centralWidget);
        text_aMagStd->setObjectName(QStringLiteral("text_aMagStd"));
        text_aMagStd->setGeometry(QRect(100, 550, 101, 20));
        text_aMagStd->setFont(font);
        label_stat_mMult_2 = new QLabel(centralWidget);
        label_stat_mMult_2->setObjectName(QStringLiteral("label_stat_mMult_2"));
        label_stat_mMult_2->setGeometry(QRect(210, 480, 81, 20));
        label_stat_mMult_2->setFont(font);
        text_mMagFOM = new QLabel(centralWidget);
        text_mMagFOM->setObjectName(QStringLiteral("text_mMagFOM"));
        text_mMagFOM->setGeometry(QRect(300, 480, 111, 20));
        text_mMagFOM->setFont(font);
        label_stat_mMult_3 = new QLabel(centralWidget);
        label_stat_mMult_3->setObjectName(QStringLiteral("label_stat_mMult_3"));
        label_stat_mMult_3->setGeometry(QRect(210, 500, 81, 20));
        label_stat_mMult_3->setFont(font);
        text_mMagStd = new QLabel(centralWidget);
        text_mMagStd->setObjectName(QStringLiteral("text_mMagStd"));
        text_mMagStd->setGeometry(QRect(300, 500, 111, 20));
        text_mMagStd->setFont(font);
        text_mDotFOM = new QLabel(centralWidget);
        text_mDotFOM->setObjectName(QStringLiteral("text_mDotFOM"));
        text_mDotFOM->setGeometry(QRect(300, 540, 111, 20));
        text_mDotFOM->setFont(font);
        label_stat_mDot_2 = new QLabel(centralWidget);
        label_stat_mDot_2->setObjectName(QStringLiteral("label_stat_mDot_2"));
        label_stat_mDot_2->setGeometry(QRect(210, 540, 81, 20));
        label_stat_mDot_2->setFont(font);
        text_mDotStd = new QLabel(centralWidget);
        text_mDotStd->setObjectName(QStringLiteral("text_mDotStd"));
        text_mDotStd->setGeometry(QRect(300, 560, 111, 20));
        text_mDotStd->setFont(font);
        label_stat_mDot_3 = new QLabel(centralWidget);
        label_stat_mDot_3->setObjectName(QStringLiteral("label_stat_mDot_3"));
        label_stat_mDot_3->setGeometry(QRect(210, 560, 81, 20));
        label_stat_mDot_3->setFont(font);
        stat_update = new QPushButton(centralWidget);
        stat_update->setObjectName(QStringLiteral("stat_update"));
        stat_update->setGeometry(QRect(150, 640, 81, 27));
        windowGUI->setCentralWidget(centralWidget);
        menuBar = new QMenuBar(windowGUI);
        menuBar->setObjectName(QStringLiteral("menuBar"));
        menuBar->setGeometry(QRect(0, 0, 1400, 25));
        windowGUI->setMenuBar(menuBar);
        mainToolBar = new QToolBar(windowGUI);
        mainToolBar->setObjectName(QStringLiteral("mainToolBar"));
        windowGUI->addToolBar(Qt::TopToolBarArea, mainToolBar);
        statusBar = new QStatusBar(windowGUI);
        statusBar->setObjectName(QStringLiteral("statusBar"));
        windowGUI->setStatusBar(statusBar);
        toolBar = new QToolBar(windowGUI);
        toolBar->setObjectName(QStringLiteral("toolBar"));
        windowGUI->addToolBar(Qt::TopToolBarArea, toolBar);

        retranslateUi(windowGUI);
        QObject::connect(rect_gBias0, SIGNAL(editingFinished()), windowGUI, SLOT(rect_read()));
        QObject::connect(rect_gBias1, SIGNAL(editingFinished()), windowGUI, SLOT(rect_read()));
        QObject::connect(rect_gBias2, SIGNAL(editingFinished()), windowGUI, SLOT(rect_read()));
        QObject::connect(rect_gMult0, SIGNAL(editingFinished()), windowGUI, SLOT(rect_read()));
        QObject::connect(rect_gMult1, SIGNAL(editingFinished()), windowGUI, SLOT(rect_read()));
        QObject::connect(rect_gMult2, SIGNAL(editingFinished()), windowGUI, SLOT(rect_read()));
        QObject::connect(rect_gMult3, SIGNAL(editingFinished()), windowGUI, SLOT(rect_read()));
        QObject::connect(rect_gMult4, SIGNAL(editingFinished()), windowGUI, SLOT(rect_read()));
        QObject::connect(rect_gMult5, SIGNAL(editingFinished()), windowGUI, SLOT(rect_read()));
        QObject::connect(rect_gMult7, SIGNAL(editingFinished()), windowGUI, SLOT(rect_read()));
        QObject::connect(rect_gMult6, SIGNAL(editingFinished()), windowGUI, SLOT(rect_read()));
        QObject::connect(rect_gMult8, SIGNAL(editingFinished()), windowGUI, SLOT(rect_read()));
        QObject::connect(rect_aBias0, SIGNAL(editingFinished()), windowGUI, SLOT(rect_read()));
        QObject::connect(rect_aBias1, SIGNAL(editingFinished()), windowGUI, SLOT(rect_read()));
        QObject::connect(rect_aBias2, SIGNAL(editingFinished()), windowGUI, SLOT(rect_read()));
        QObject::connect(rect_aMult0, SIGNAL(editingFinished()), windowGUI, SLOT(rect_read()));
        QObject::connect(rect_aMult1, SIGNAL(editingFinished()), windowGUI, SLOT(rect_read()));
        QObject::connect(rect_aMult2, SIGNAL(editingFinished()), windowGUI, SLOT(rect_read()));
        QObject::connect(rect_aMult3, SIGNAL(editingFinished()), windowGUI, SLOT(rect_read()));
        QObject::connect(rect_aMult4, SIGNAL(editingFinished()), windowGUI, SLOT(rect_read()));
        QObject::connect(rect_aMult5, SIGNAL(editingFinished()), windowGUI, SLOT(rect_read()));
        QObject::connect(rect_aMult6, SIGNAL(editingFinished()), windowGUI, SLOT(rect_read()));
        QObject::connect(rect_aMult7, SIGNAL(editingFinished()), windowGUI, SLOT(rect_read()));
        QObject::connect(rect_aMult8, SIGNAL(editingFinished()), windowGUI, SLOT(rect_read()));
        QObject::connect(rect_mBias0, SIGNAL(editingFinished()), windowGUI, SLOT(rect_read()));
        QObject::connect(rect_mBias1, SIGNAL(editingFinished()), windowGUI, SLOT(rect_read()));
        QObject::connect(rect_mBias2, SIGNAL(editingFinished()), windowGUI, SLOT(rect_read()));
        QObject::connect(rect_mMult0, SIGNAL(editingFinished()), windowGUI, SLOT(rect_read()));
        QObject::connect(rect_mMult1, SIGNAL(editingFinished()), windowGUI, SLOT(rect_read()));
        QObject::connect(rect_mMult2, SIGNAL(editingFinished()), windowGUI, SLOT(rect_read()));
        QObject::connect(rect_mMult3, SIGNAL(editingFinished()), windowGUI, SLOT(rect_read()));
        QObject::connect(rect_mMult4, SIGNAL(editingFinished()), windowGUI, SLOT(rect_read()));
        QObject::connect(rect_mMult5, SIGNAL(editingFinished()), windowGUI, SLOT(rect_read()));
        QObject::connect(rect_mMult6, SIGNAL(editingFinished()), windowGUI, SLOT(rect_read()));
        QObject::connect(rect_mMult7, SIGNAL(editingFinished()), windowGUI, SLOT(rect_read()));
        QObject::connect(rect_mMult8, SIGNAL(editingFinished()), windowGUI, SLOT(rect_read()));
        QObject::connect(core_isGyro, SIGNAL(clicked()), windowGUI, SLOT(core_read()));
        QObject::connect(core_isAccl, SIGNAL(clicked()), windowGUI, SLOT(core_read()));
        QObject::connect(core_isMagn, SIGNAL(clicked()), windowGUI, SLOT(core_read()));
        QObject::connect(core_isPredict, SIGNAL(clicked()), windowGUI, SLOT(core_read()));
        QObject::connect(core_isFOM, SIGNAL(clicked()), windowGUI, SLOT(core_read()));
        QObject::connect(core_isTran, SIGNAL(clicked()), windowGUI, SLOT(core_read()));
        QObject::connect(core_gScale, SIGNAL(editingFinished()), windowGUI, SLOT(core_read()));
        QObject::connect(core_tranAlpha, SIGNAL(editingFinished()), windowGUI, SLOT(core_read()));
        QObject::connect(disp_scaleGyro, SIGNAL(editingFinished()), windowGUI, SLOT(glWidget_update()));
        QObject::connect(disp_scaleAccl, SIGNAL(editingFinished()), windowGUI, SLOT(glWidget_update()));
        QObject::connect(disp_scaleMagn, SIGNAL(editingFinished()), windowGUI, SLOT(glWidget_update()));
        QObject::connect(disp_scaleIMU, SIGNAL(editingFinished()), windowGUI, SLOT(glWidget_update()));
        QObject::connect(disp_vectCor, SIGNAL(clicked()), windowGUI, SLOT(glWidget_update()));
        QObject::connect(disp_vectRaw, SIGNAL(clicked()), windowGUI, SLOT(glWidget_update()));
        QObject::connect(disp_vectFltr, SIGNAL(clicked()), windowGUI, SLOT(glWidget_update()));
        QObject::connect(core_aWeight, SIGNAL(editingFinished()), windowGUI, SLOT(core_read()));
        QObject::connect(core_aMag, SIGNAL(editingFinished()), windowGUI, SLOT(core_read()));
        QObject::connect(core_aMagThresh, SIGNAL(editingFinished()), windowGUI, SLOT(core_read()));
        QObject::connect(core_mWeight, SIGNAL(editingFinished()), windowGUI, SLOT(core_read()));
        QObject::connect(core_mMag, SIGNAL(editingFinished()), windowGUI, SLOT(core_read()));
        QObject::connect(core_mMagThresh, SIGNAL(editingFinished()), windowGUI, SLOT(core_read()));
        QObject::connect(core_mDot, SIGNAL(editingFinished()), windowGUI, SLOT(core_read()));
        QObject::connect(core_mDotThresh, SIGNAL(editingFinished()), windowGUI, SLOT(core_read()));
        QObject::connect(pnts_isGyro, SIGNAL(clicked()), windowGUI, SLOT(pnts_read()));
        QObject::connect(pnts_isAccl, SIGNAL(clicked()), windowGUI, SLOT(pnts_read()));
        QObject::connect(pnts_isMagn, SIGNAL(clicked()), windowGUI, SLOT(pnts_read()));
        QObject::connect(pnts_tHold, SIGNAL(editingFinished()), windowGUI, SLOT(pnts_read()));
        QObject::connect(pnts_tStable, SIGNAL(editingFinished()), windowGUI, SLOT(pnts_read()));
        QObject::connect(pnts_gAlpha, SIGNAL(editingFinished()), windowGUI, SLOT(pnts_read()));
        QObject::connect(pnts_gThresh, SIGNAL(editingFinished()), windowGUI, SLOT(pnts_read()));
        QObject::connect(pnts_aAlpha, SIGNAL(editingFinished()), windowGUI, SLOT(pnts_read()));
        QObject::connect(pnts_aThresh, SIGNAL(editingFinished()), windowGUI, SLOT(pnts_read()));
        QObject::connect(pnts_mAlpha, SIGNAL(editingFinished()), windowGUI, SLOT(pnts_read()));
        QObject::connect(pnts_mThresh, SIGNAL(editingFinished()), windowGUI, SLOT(pnts_read()));
        QObject::connect(stat_alpha, SIGNAL(editingFinished()), windowGUI, SLOT(stat_read()));
        QObject::connect(rect_enable, SIGNAL(clicked()), windowGUI, SLOT(rect_read()));
        QObject::connect(pnts_enable, SIGNAL(clicked()), windowGUI, SLOT(pnts_read()));
        QObject::connect(stat_enable, SIGNAL(clicked()), windowGUI, SLOT(stat_read()));
        QObject::connect(calb_enable, SIGNAL(clicked()), windowGUI, SLOT(calb_read()));

        QMetaObject::connectSlotsByName(windowGUI);
    } // setupUi

    void retranslateUi(QMainWindow *windowGUI)
    {
        windowGUI->setWindowTitle(QApplication::translate("windowGUI", "Real Time Display Tool", 0));
        disp_scaleGyro->setText(QApplication::translate("windowGUI", "1000", 0));
        disp_scaleAccl->setText(QApplication::translate("windowGUI", "2500", 0));
        disp_scaleMagn->setText(QApplication::translate("windowGUI", "5000", 0));
        disp_scaleIMU->setText(QApplication::translate("windowGUI", "1000", 0));
        disp_enableGyro->setText(QApplication::translate("windowGUI", "gyroscope", 0));
        disp_enableAccl->setText(QApplication::translate("windowGUI", "accelerometer", 0));
        disp_enableMagn->setText(QApplication::translate("windowGUI", "magnetometer", 0));
        disp_enableIMU->setText(QApplication::translate("windowGUI", "IMU", 0));
        label_display->setText(QApplication::translate("windowGUI", "Display Options", 0));
        core_isGyro->setText(QApplication::translate("windowGUI", "gyro", 0));
        core_isAccl->setText(QApplication::translate("windowGUI", "accl", 0));
        core_isMagn->setText(QApplication::translate("windowGUI", "magn", 0));
        view_up->setText(QApplication::translate("windowGUI", "up", 0));
        view_side1->setText(QApplication::translate("windowGUI", "side 1", 0));
        view_side2->setText(QApplication::translate("windowGUI", "side 2", 0));
        select_reference->setText(QApplication::translate("windowGUI", "set reference", 0));
        select_reset->setText(QApplication::translate("windowGUI", "reset", 0));
        rect_gBias0->setText(QApplication::translate("windowGUI", "0.0", 0));
        rect_gBias1->setText(QApplication::translate("windowGUI", "0.0", 0));
        rect_gBias2->setText(QApplication::translate("windowGUI", "0.0", 0));
        rect_gMult1->setText(QApplication::translate("windowGUI", "0.0", 0));
        rect_gMult2->setText(QApplication::translate("windowGUI", "0.0", 0));
        rect_gMult0->setText(QApplication::translate("windowGUI", "1.0", 0));
        rect_gMult5->setText(QApplication::translate("windowGUI", "0.0", 0));
        rect_gMult3->setText(QApplication::translate("windowGUI", "0.0", 0));
        rect_gMult4->setText(QApplication::translate("windowGUI", "1.0", 0));
        rect_gMult8->setText(QApplication::translate("windowGUI", "1.0", 0));
        rect_gMult6->setText(QApplication::translate("windowGUI", "0.0", 0));
        rect_gMult7->setText(QApplication::translate("windowGUI", "0.0", 0));
        label_rect_gBias->setText(QApplication::translate("windowGUI", "gyroscope biases", 0));
        lable_rect_gMult->setText(QApplication::translate("windowGUI", "gyroscope transformation matrix", 0));
        rect_aBias1->setText(QApplication::translate("windowGUI", "0.0", 0));
        rect_aMult2->setText(QApplication::translate("windowGUI", "0.0", 0));
        rect_aMult7->setText(QApplication::translate("windowGUI", "0.0", 0));
        rect_aMult1->setText(QApplication::translate("windowGUI", "0.0", 0));
        rect_aMult0->setText(QApplication::translate("windowGUI", "1.0", 0));
        rect_aMult3->setText(QApplication::translate("windowGUI", "0.0", 0));
        label_rect_aMult->setText(QApplication::translate("windowGUI", "accelerometer transformation matrix", 0));
        rect_aMult8->setText(QApplication::translate("windowGUI", "1.0", 0));
        rect_aBias2->setText(QApplication::translate("windowGUI", "0.0", 0));
        rect_aBias0->setText(QApplication::translate("windowGUI", "0.0", 0));
        rect_aMult5->setText(QApplication::translate("windowGUI", "0.0", 0));
        rect_aMult6->setText(QApplication::translate("windowGUI", "0.0", 0));
        label_rect_aBias->setText(QApplication::translate("windowGUI", "accelerometer biases", 0));
        rect_aMult4->setText(QApplication::translate("windowGUI", "1.0", 0));
        rect_mBias1->setText(QApplication::translate("windowGUI", "0.0", 0));
        rect_mMult3->setText(QApplication::translate("windowGUI", "0.0", 0));
        rect_mMult2->setText(QApplication::translate("windowGUI", "0.0", 0));
        rect_mMult6->setText(QApplication::translate("windowGUI", "0.0", 0));
        rect_mMult1->setText(QApplication::translate("windowGUI", "0.0", 0));
        label_rect_mMult->setText(QApplication::translate("windowGUI", "magnetometer transformation matrix", 0));
        rect_mBias0->setText(QApplication::translate("windowGUI", "0.0", 0));
        rect_mMult0->setText(QApplication::translate("windowGUI", "1.0", 0));
        rect_mBias2->setText(QApplication::translate("windowGUI", "0.0", 0));
        rect_mMult4->setText(QApplication::translate("windowGUI", "1.0", 0));
        label_rect_mBias->setText(QApplication::translate("windowGUI", "magnetometer biases", 0));
        rect_mMult8->setText(QApplication::translate("windowGUI", "1.0", 0));
        rect_mMult5->setText(QApplication::translate("windowGUI", "0.0", 0));
        rect_mMult7->setText(QApplication::translate("windowGUI", "0.0", 0));
        label_core_gScale->setText(QApplication::translate("windowGUI", "gScale", 0));
        label_core->setText(QApplication::translate("windowGUI", "Core Config", 0));
        label_stat_gBias->setText(QApplication::translate("windowGUI", "gBias:", 0));
        label_stat_aMag->setText(QApplication::translate("windowGUI", "aMag:", 0));
        label_stat_mMult->setText(QApplication::translate("windowGUI", "mMag:", 0));
        label_stat_mDot->setText(QApplication::translate("windowGUI", "mDot:", 0));
        text_aMag->setText(QApplication::translate("windowGUI", "-", 0));
        text_mMag->setText(QApplication::translate("windowGUI", "-", 0));
        text_mDot->setText(QApplication::translate("windowGUI", "-", 0));
        text_gBias->setText(QApplication::translate("windowGUI", "-", 0));
        rect_open->setText(QApplication::translate("windowGUI", "Open", 0));
        rect_save->setText(QApplication::translate("windowGUI", "Save", 0));
        core_isPredict->setText(QApplication::translate("windowGUI", "predict", 0));
        core_isFOM->setText(QApplication::translate("windowGUI", "FOM", 0));
        core_isTran->setText(QApplication::translate("windowGUI", "tran", 0));
        core_gScale->setText(QApplication::translate("windowGUI", "1.0", 0));
        core_tranAlpha->setText(QApplication::translate("windowGUI", "1.0", 0));
        label_core_tranAlpha->setText(QApplication::translate("windowGUI", "tranAlpha", 0));
        core_save->setText(QApplication::translate("windowGUI", "Save", 0));
        core_open->setText(QApplication::translate("windowGUI", "Open", 0));
        disp_vectRaw->setText(QApplication::translate("windowGUI", "Raw", 0));
        disp_vectCor->setText(QApplication::translate("windowGUI", "Corrected", 0));
        disp_vectFltr->setText(QApplication::translate("windowGUI", "Filtered", 0));
        label_core_aMagThresh->setText(QApplication::translate("windowGUI", "aMagThresh", 0));
        core_aWeight->setText(QApplication::translate("windowGUI", "0.0", 0));
        label_core_aWeight->setText(QApplication::translate("windowGUI", "aWeight", 0));
        label_core_aMag->setText(QApplication::translate("windowGUI", "aMag", 0));
        core_aMagThresh->setText(QApplication::translate("windowGUI", "0.0", 0));
        core_aMag->setText(QApplication::translate("windowGUI", "0.0", 0));
        core_mMag->setText(QApplication::translate("windowGUI", "0.0", 0));
        label_core_mWeight->setText(QApplication::translate("windowGUI", "mWeight", 0));
        label_core_mMag->setText(QApplication::translate("windowGUI", "mMag", 0));
        core_mWeight->setText(QApplication::translate("windowGUI", "0.0", 0));
        label_core_mMagThresh->setText(QApplication::translate("windowGUI", "mMagThresh", 0));
        core_mMagThresh->setText(QApplication::translate("windowGUI", "0.0", 0));
        core_mDot->setText(QApplication::translate("windowGUI", "0.0", 0));
        label_core_mDot->setText(QApplication::translate("windowGUI", "mDot", 0));
        label_core_mDotThresh->setText(QApplication::translate("windowGUI", "mDotThresh", 0));
        core_mDotThresh->setText(QApplication::translate("windowGUI", "0.0", 0));
        pnts_isGyro->setText(QApplication::translate("windowGUI", "gyro", 0));
        pnts_isMagn->setText(QApplication::translate("windowGUI", "magn", 0));
        pnts_isAccl->setText(QApplication::translate("windowGUI", "accl", 0));
        pnts_tHold->setText(QApplication::translate("windowGUI", "1.0", 0));
        label_pnts_tHold->setText(QApplication::translate("windowGUI", "tHold", 0));
        pnts_tStable->setText(QApplication::translate("windowGUI", "1.0", 0));
        label_pnts_tStable->setText(QApplication::translate("windowGUI", "tStable", 0));
        pnts_gThresh->setText(QApplication::translate("windowGUI", "1.0", 0));
        pnts_gAlpha->setText(QApplication::translate("windowGUI", "1.0", 0));
        label_pnts_gAlpha->setText(QApplication::translate("windowGUI", "gAlpha", 0));
        label_pnts_gThresh->setText(QApplication::translate("windowGUI", "gThresh", 0));
        pnts_aThresh->setText(QApplication::translate("windowGUI", "1.0", 0));
        label_pnts_aAlpha->setText(QApplication::translate("windowGUI", "aAlpha", 0));
        pnts_aAlpha->setText(QApplication::translate("windowGUI", "1.0", 0));
        label_pnts_aThresh->setText(QApplication::translate("windowGUI", "aThresh", 0));
        label_pnts_mAlpha->setText(QApplication::translate("windowGUI", "mAlpha", 0));
        pnts_mAlpha->setText(QApplication::translate("windowGUI", "1.0", 0));
        pnts_mThresh->setText(QApplication::translate("windowGUI", "1.0", 0));
        label_pnts_mThresh->setText(QApplication::translate("windowGUI", "mThresh", 0));
        pnts_save->setText(QApplication::translate("windowGUI", "Save", 0));
        pnts_open->setText(QApplication::translate("windowGUI", "Open", 0));
        calb_type->clear();
        calb_type->insertItems(0, QStringList()
         << QApplication::translate("windowGUI", "1pnt Gyro", 0)
         << QApplication::translate("windowGUI", "2pnt Gyro", 0)
         << QApplication::translate("windowGUI", "4pnt Magn", 0)
         << QApplication::translate("windowGUI", "6pnt Full", 0)
        );
        stat_alpha->setText(QApplication::translate("windowGUI", "1.0", 0));
        label_stat_alpha->setText(QApplication::translate("windowGUI", "alpha", 0));
        stat_save->setText(QApplication::translate("windowGUI", "Save", 0));
        stat_open->setText(QApplication::translate("windowGUI", "Open", 0));
        calb_go->setText(QApplication::translate("windowGUI", "Go", 0));
        pnts_val->setText(QApplication::translate("windowGUI", "0.0", 0));
        label_calb_val->setText(QApplication::translate("windowGUI", "val", 0));
        pnts_enable->setText(QApplication::translate("windowGUI", "Pnts Config", 0));
        rect_enable->setText(QApplication::translate("windowGUI", "Rect Config", 0));
        stat_enable->setText(QApplication::translate("windowGUI", "Stat Config", 0));
        calb_enable->setText(QApplication::translate("windowGUI", "Calb Config/Control", 0));
        calb_save->setText(QApplication::translate("windowGUI", "Save", 0));
        calb_open->setText(QApplication::translate("windowGUI", "Open", 0));
        text_state->setText(QApplication::translate("windowGUI", "reset", 0));
        text_gBiasStd->setText(QApplication::translate("windowGUI", "-", 0));
        label_stat_gBiasStd->setText(QApplication::translate("windowGUI", "gBiasStd:", 0));
        label_stat_aMag_2->setText(QApplication::translate("windowGUI", "aMagFOM:", 0));
        text_aMagFOM->setText(QApplication::translate("windowGUI", "-", 0));
        label_stat_aMag_3->setText(QApplication::translate("windowGUI", "aMagStd:", 0));
        text_aMagStd->setText(QApplication::translate("windowGUI", "-", 0));
        label_stat_mMult_2->setText(QApplication::translate("windowGUI", "mMagFOM:", 0));
        text_mMagFOM->setText(QApplication::translate("windowGUI", "-", 0));
        label_stat_mMult_3->setText(QApplication::translate("windowGUI", "mMagStd:", 0));
        text_mMagStd->setText(QApplication::translate("windowGUI", "-", 0));
        text_mDotFOM->setText(QApplication::translate("windowGUI", "-", 0));
        label_stat_mDot_2->setText(QApplication::translate("windowGUI", "mDotFOM:", 0));
        text_mDotStd->setText(QApplication::translate("windowGUI", "-", 0));
        label_stat_mDot_3->setText(QApplication::translate("windowGUI", "mDotStd:", 0));
        stat_update->setText(QApplication::translate("windowGUI", "Update", 0));
        toolBar->setWindowTitle(QApplication::translate("windowGUI", "toolBar", 0));
    } // retranslateUi

};

namespace Ui {
    class windowGUI: public Ui_windowGUI {};
} // namespace Ui

QT_END_NAMESPACE

#endif // UI_WINDOWGUI_H
