/********************************************************************************
** Form generated from reading UI file 'windowGUI.ui'
**
** Created by: Qt User Interface Compiler version 5.5.1
**
** WARNING! All changes made in this file will be lost when recompiling UI file!
********************************************************************************/

#ifndef UI_WINDOWGUI_H
#define UI_WINDOWGUI_H

#include <QtCore/QVariant>
#include <QtWidgets/QAction>
#include <QtWidgets/QApplication>
#include <QtWidgets/QButtonGroup>
#include <QtWidgets/QCheckBox>
#include <QtWidgets/QFrame>
#include <QtWidgets/QHeaderView>
#include <QtWidgets/QLabel>
#include <QtWidgets/QLineEdit>
#include <QtWidgets/QMainWindow>
#include <QtWidgets/QMenuBar>
#include <QtWidgets/QPushButton>
#include <QtWidgets/QRadioButton>
#include <QtWidgets/QStatusBar>
#include <QtWidgets/QToolBar>
#include <QtWidgets/QWidget>
#include "glWidget.h"

QT_BEGIN_NAMESPACE

class Ui_windowGUI
{
public:
    QWidget *centralWidget;
    QLineEdit *dispScaleGyro;
    QLineEdit *dispScaleAccl;
    QLineEdit *dispScaleMagn;
    QLineEdit *dispScaleIMU;
    QCheckBox *dispEnableGyro;
    QCheckBox *dispEnableAccl;
    QFrame *line_v1;
    QCheckBox *dispEnableMagn;
    QCheckBox *dispEnableIMU;
    QLabel *labelDisplay;
    QFrame *line_h1;
    QLabel *labelControls;
    QCheckBox *noGyro;
    QCheckBox *noAccl;
    QCheckBox *noMagn;
    QPushButton *viewUp;
    QPushButton *viewSide1;
    QPushButton *viewSide2;
    QLineEdit *up0;
    QLabel *labelUp;
    QLineEdit *up1;
    QLineEdit *up2;
    QPushButton *selectReference;
    QPushButton *selectReset;
    QPushButton *selectDeadRecon;
    QLineEdit *gBias0;
    QLineEdit *gBias1;
    QLineEdit *gBias2;
    QLineEdit *gMult1;
    QLineEdit *gMult2;
    QLineEdit *gMult0;
    QLineEdit *gMult5;
    QLineEdit *gMult3;
    QLineEdit *gMult4;
    QLineEdit *gMult8;
    QLineEdit *gMult6;
    QLineEdit *gMult7;
    QLabel *labelCorrect1;
    QLabel *labelCorrect2;
    QLineEdit *aBias1;
    QLineEdit *aMult2;
    QLineEdit *aMult7;
    QLineEdit *aMult1;
    QLineEdit *aMult0;
    QLineEdit *aMult3;
    QLabel *labelCorrect4;
    QLineEdit *aMult8;
    QLineEdit *aBias2;
    QLineEdit *aBias0;
    QLineEdit *aMult5;
    QLineEdit *aMult6;
    QLabel *labelCorrect3;
    QLineEdit *aMult4;
    QLineEdit *mBias1;
    QLineEdit *mMult3;
    QLineEdit *mMult2;
    QLineEdit *mMult6;
    QLineEdit *mMult1;
    QLabel *labelCorrect6;
    QLineEdit *mBias0;
    QLineEdit *mMult0;
    QLineEdit *mBias2;
    QLineEdit *mMult4;
    QLabel *labelCorrect5;
    QLineEdit *mMult8;
    QLineEdit *mMult5;
    QLineEdit *mMult7;
    QFrame *line_h2;
    QLabel *labelCore1;
    QLabel *labelCore;
    QFrame *line_v2;
    QLabel *labelGyroBias;
    QLabel *labelGyroScale;
    QLabel *labelAcclScale;
    QLabel *labelAcclBias;
    QLabel *labelMagnBias;
    QLabel *labelAcclMag;
    QLabel *labelMagnMag;
    QLabel *labelMagnAng;
    QLabel *textMagnBias;
    QLabel *textAcclMag;
    QLabel *textGyroScale;
    QLabel *textAcclScale;
    QLabel *textAcclBias;
    QLabel *textMagnMag;
    QLabel *textMagnAng;
    QLabel *textGyroBias;
    GLWidget *widget;
    QLabel *labelCorrect;
    QPushButton *calibOpen;
    QPushButton *calibSave;
    QCheckBox *noStable;
    QCheckBox *noFOM;
    QCheckBox *noMove;
    QLineEdit *gThreshVal;
    QLineEdit *gThreshTime;
    QLabel *labelCore2;
    QPushButton *configSave;
    QPushButton *configOpen;
    QRadioButton *dispVectRaw;
    QRadioButton *dispVectCor;
    QRadioButton *dispVectFltr;
    QLabel *labelCore5;
    QLineEdit *aWeight;
    QLabel *labelCore3;
    QLabel *labelCore4;
    QLineEdit *aMagThresh;
    QLineEdit *aMag;
    QLineEdit *mMag;
    QLabel *labelCore6;
    QLabel *labelCore7;
    QLineEdit *mWeight;
    QLabel *labelCore8;
    QLineEdit *mMagThresh;
    QLineEdit *mAng;
    QLabel *labelCore9;
    QLabel *labelCore10;
    QLineEdit *mAngThresh;
    QLineEdit *moveAlpha;
    QLabel *labelCore11;
    QMenuBar *menuBar;
    QToolBar *mainToolBar;
    QStatusBar *statusBar;
    QToolBar *toolBar;

    void setupUi(QMainWindow *windowGUI)
    {
        if (windowGUI->objectName().isEmpty())
            windowGUI->setObjectName(QStringLiteral("windowGUI"));
        windowGUI->resize(1400, 770);
        QFont font;
        font.setBold(false);
        font.setWeight(50);
        windowGUI->setFont(font);
        centralWidget = new QWidget(windowGUI);
        centralWidget->setObjectName(QStringLiteral("centralWidget"));
        dispScaleGyro = new QLineEdit(centralWidget);
        dispScaleGyro->setObjectName(QStringLiteral("dispScaleGyro"));
        dispScaleGyro->setGeometry(QRect(430, 40, 101, 27));
        dispScaleAccl = new QLineEdit(centralWidget);
        dispScaleAccl->setObjectName(QStringLiteral("dispScaleAccl"));
        dispScaleAccl->setGeometry(QRect(430, 80, 101, 27));
        dispScaleMagn = new QLineEdit(centralWidget);
        dispScaleMagn->setObjectName(QStringLiteral("dispScaleMagn"));
        dispScaleMagn->setGeometry(QRect(430, 120, 101, 27));
        dispScaleIMU = new QLineEdit(centralWidget);
        dispScaleIMU->setObjectName(QStringLiteral("dispScaleIMU"));
        dispScaleIMU->setGeometry(QRect(430, 160, 101, 27));
        dispEnableGyro = new QCheckBox(centralWidget);
        dispEnableGyro->setObjectName(QStringLiteral("dispEnableGyro"));
        dispEnableGyro->setGeometry(QRect(540, 40, 141, 22));
        dispEnableGyro->setChecked(true);
        dispEnableAccl = new QCheckBox(centralWidget);
        dispEnableAccl->setObjectName(QStringLiteral("dispEnableAccl"));
        dispEnableAccl->setGeometry(QRect(540, 80, 141, 22));
        dispEnableAccl->setChecked(true);
        line_v1 = new QFrame(centralWidget);
        line_v1->setObjectName(QStringLiteral("line_v1"));
        line_v1->setGeometry(QRect(710, 0, 20, 701));
        line_v1->setFrameShape(QFrame::VLine);
        line_v1->setFrameShadow(QFrame::Sunken);
        dispEnableMagn = new QCheckBox(centralWidget);
        dispEnableMagn->setObjectName(QStringLiteral("dispEnableMagn"));
        dispEnableMagn->setGeometry(QRect(540, 120, 141, 22));
        dispEnableMagn->setChecked(true);
        dispEnableIMU = new QCheckBox(centralWidget);
        dispEnableIMU->setObjectName(QStringLiteral("dispEnableIMU"));
        dispEnableIMU->setGeometry(QRect(540, 160, 141, 22));
        labelDisplay = new QLabel(centralWidget);
        labelDisplay->setObjectName(QStringLiteral("labelDisplay"));
        labelDisplay->setGeometry(QRect(510, 0, 121, 17));
        QFont font1;
        font1.setBold(true);
        font1.setWeight(75);
        labelDisplay->setFont(font1);
        line_h1 = new QFrame(centralWidget);
        line_h1->setObjectName(QStringLiteral("line_h1"));
        line_h1->setGeometry(QRect(430, 280, 281, 16));
        line_h1->setFrameShape(QFrame::HLine);
        line_h1->setFrameShadow(QFrame::Sunken);
        labelControls = new QLabel(centralWidget);
        labelControls->setObjectName(QStringLiteral("labelControls"));
        labelControls->setGeometry(QRect(520, 300, 121, 17));
        labelControls->setFont(font1);
        noGyro = new QCheckBox(centralWidget);
        noGyro->setObjectName(QStringLiteral("noGyro"));
        noGyro->setGeometry(QRect(730, 40, 97, 22));
        noAccl = new QCheckBox(centralWidget);
        noAccl->setObjectName(QStringLiteral("noAccl"));
        noAccl->setGeometry(QRect(840, 40, 97, 22));
        noMagn = new QCheckBox(centralWidget);
        noMagn->setObjectName(QStringLiteral("noMagn"));
        noMagn->setGeometry(QRect(940, 40, 97, 22));
        viewUp = new QPushButton(centralWidget);
        viewUp->setObjectName(QStringLiteral("viewUp"));
        viewUp->setGeometry(QRect(430, 240, 71, 27));
        viewSide1 = new QPushButton(centralWidget);
        viewSide1->setObjectName(QStringLiteral("viewSide1"));
        viewSide1->setGeometry(QRect(530, 240, 71, 27));
        viewSide2 = new QPushButton(centralWidget);
        viewSide2->setObjectName(QStringLiteral("viewSide2"));
        viewSide2->setGeometry(QRect(630, 240, 71, 27));
        up0 = new QLineEdit(centralWidget);
        up0->setObjectName(QStringLiteral("up0"));
        up0->setGeometry(QRect(480, 330, 71, 27));
        labelUp = new QLabel(centralWidget);
        labelUp->setObjectName(QStringLiteral("labelUp"));
        labelUp->setGeometry(QRect(440, 335, 31, 17));
        labelUp->setFont(font);
        up1 = new QLineEdit(centralWidget);
        up1->setObjectName(QStringLiteral("up1"));
        up1->setGeometry(QRect(560, 330, 71, 27));
        up2 = new QLineEdit(centralWidget);
        up2->setObjectName(QStringLiteral("up2"));
        up2->setGeometry(QRect(640, 330, 71, 27));
        selectReference = new QPushButton(centralWidget);
        selectReference->setObjectName(QStringLiteral("selectReference"));
        selectReference->setGeometry(QRect(430, 370, 111, 27));
        selectReset = new QPushButton(centralWidget);
        selectReset->setObjectName(QStringLiteral("selectReset"));
        selectReset->setGeometry(QRect(550, 370, 61, 27));
        selectDeadRecon = new QPushButton(centralWidget);
        selectDeadRecon->setObjectName(QStringLiteral("selectDeadRecon"));
        selectDeadRecon->setGeometry(QRect(620, 370, 91, 27));
        gBias0 = new QLineEdit(centralWidget);
        gBias0->setObjectName(QStringLiteral("gBias0"));
        gBias0->setGeometry(QRect(1070, 50, 101, 27));
        gBias1 = new QLineEdit(centralWidget);
        gBias1->setObjectName(QStringLiteral("gBias1"));
        gBias1->setGeometry(QRect(1180, 50, 101, 27));
        gBias2 = new QLineEdit(centralWidget);
        gBias2->setObjectName(QStringLiteral("gBias2"));
        gBias2->setGeometry(QRect(1290, 50, 101, 27));
        gMult1 = new QLineEdit(centralWidget);
        gMult1->setObjectName(QStringLiteral("gMult1"));
        gMult1->setGeometry(QRect(1180, 110, 101, 27));
        gMult2 = new QLineEdit(centralWidget);
        gMult2->setObjectName(QStringLiteral("gMult2"));
        gMult2->setGeometry(QRect(1290, 110, 101, 27));
        gMult0 = new QLineEdit(centralWidget);
        gMult0->setObjectName(QStringLiteral("gMult0"));
        gMult0->setGeometry(QRect(1070, 110, 101, 27));
        gMult5 = new QLineEdit(centralWidget);
        gMult5->setObjectName(QStringLiteral("gMult5"));
        gMult5->setGeometry(QRect(1290, 140, 101, 27));
        gMult3 = new QLineEdit(centralWidget);
        gMult3->setObjectName(QStringLiteral("gMult3"));
        gMult3->setGeometry(QRect(1070, 140, 101, 27));
        gMult4 = new QLineEdit(centralWidget);
        gMult4->setObjectName(QStringLiteral("gMult4"));
        gMult4->setGeometry(QRect(1180, 140, 101, 27));
        gMult8 = new QLineEdit(centralWidget);
        gMult8->setObjectName(QStringLiteral("gMult8"));
        gMult8->setGeometry(QRect(1290, 170, 101, 27));
        gMult6 = new QLineEdit(centralWidget);
        gMult6->setObjectName(QStringLiteral("gMult6"));
        gMult6->setGeometry(QRect(1070, 170, 101, 27));
        gMult7 = new QLineEdit(centralWidget);
        gMult7->setObjectName(QStringLiteral("gMult7"));
        gMult7->setGeometry(QRect(1180, 170, 101, 27));
        labelCorrect1 = new QLabel(centralWidget);
        labelCorrect1->setObjectName(QStringLiteral("labelCorrect1"));
        labelCorrect1->setGeometry(QRect(1170, 30, 121, 20));
        labelCorrect1->setFont(font);
        labelCorrect2 = new QLabel(centralWidget);
        labelCorrect2->setObjectName(QStringLiteral("labelCorrect2"));
        labelCorrect2->setGeometry(QRect(1110, 90, 231, 20));
        labelCorrect2->setFont(font);
        aBias1 = new QLineEdit(centralWidget);
        aBias1->setObjectName(QStringLiteral("aBias1"));
        aBias1->setGeometry(QRect(1180, 240, 101, 27));
        aMult2 = new QLineEdit(centralWidget);
        aMult2->setObjectName(QStringLiteral("aMult2"));
        aMult2->setGeometry(QRect(1290, 300, 101, 27));
        aMult7 = new QLineEdit(centralWidget);
        aMult7->setObjectName(QStringLiteral("aMult7"));
        aMult7->setGeometry(QRect(1180, 360, 101, 27));
        aMult1 = new QLineEdit(centralWidget);
        aMult1->setObjectName(QStringLiteral("aMult1"));
        aMult1->setGeometry(QRect(1180, 300, 101, 27));
        aMult0 = new QLineEdit(centralWidget);
        aMult0->setObjectName(QStringLiteral("aMult0"));
        aMult0->setGeometry(QRect(1070, 300, 101, 27));
        aMult3 = new QLineEdit(centralWidget);
        aMult3->setObjectName(QStringLiteral("aMult3"));
        aMult3->setGeometry(QRect(1070, 330, 101, 27));
        labelCorrect4 = new QLabel(centralWidget);
        labelCorrect4->setObjectName(QStringLiteral("labelCorrect4"));
        labelCorrect4->setGeometry(QRect(1100, 280, 271, 20));
        labelCorrect4->setFont(font);
        aMult8 = new QLineEdit(centralWidget);
        aMult8->setObjectName(QStringLiteral("aMult8"));
        aMult8->setGeometry(QRect(1290, 360, 101, 27));
        aBias2 = new QLineEdit(centralWidget);
        aBias2->setObjectName(QStringLiteral("aBias2"));
        aBias2->setGeometry(QRect(1290, 240, 101, 27));
        aBias0 = new QLineEdit(centralWidget);
        aBias0->setObjectName(QStringLiteral("aBias0"));
        aBias0->setGeometry(QRect(1070, 240, 101, 27));
        aMult5 = new QLineEdit(centralWidget);
        aMult5->setObjectName(QStringLiteral("aMult5"));
        aMult5->setGeometry(QRect(1290, 330, 101, 27));
        aMult6 = new QLineEdit(centralWidget);
        aMult6->setObjectName(QStringLiteral("aMult6"));
        aMult6->setGeometry(QRect(1070, 360, 101, 27));
        labelCorrect3 = new QLabel(centralWidget);
        labelCorrect3->setObjectName(QStringLiteral("labelCorrect3"));
        labelCorrect3->setGeometry(QRect(1160, 220, 161, 20));
        labelCorrect3->setFont(font);
        aMult4 = new QLineEdit(centralWidget);
        aMult4->setObjectName(QStringLiteral("aMult4"));
        aMult4->setGeometry(QRect(1180, 330, 101, 27));
        mBias1 = new QLineEdit(centralWidget);
        mBias1->setObjectName(QStringLiteral("mBias1"));
        mBias1->setGeometry(QRect(1180, 430, 101, 27));
        mMult3 = new QLineEdit(centralWidget);
        mMult3->setObjectName(QStringLiteral("mMult3"));
        mMult3->setGeometry(QRect(1070, 520, 101, 27));
        mMult2 = new QLineEdit(centralWidget);
        mMult2->setObjectName(QStringLiteral("mMult2"));
        mMult2->setGeometry(QRect(1290, 490, 101, 27));
        mMult6 = new QLineEdit(centralWidget);
        mMult6->setObjectName(QStringLiteral("mMult6"));
        mMult6->setGeometry(QRect(1070, 550, 101, 27));
        mMult1 = new QLineEdit(centralWidget);
        mMult1->setObjectName(QStringLiteral("mMult1"));
        mMult1->setGeometry(QRect(1180, 490, 101, 27));
        labelCorrect6 = new QLabel(centralWidget);
        labelCorrect6->setObjectName(QStringLiteral("labelCorrect6"));
        labelCorrect6->setGeometry(QRect(1100, 470, 261, 20));
        labelCorrect6->setFont(font);
        mBias0 = new QLineEdit(centralWidget);
        mBias0->setObjectName(QStringLiteral("mBias0"));
        mBias0->setGeometry(QRect(1070, 430, 101, 27));
        mMult0 = new QLineEdit(centralWidget);
        mMult0->setObjectName(QStringLiteral("mMult0"));
        mMult0->setGeometry(QRect(1070, 490, 101, 27));
        mBias2 = new QLineEdit(centralWidget);
        mBias2->setObjectName(QStringLiteral("mBias2"));
        mBias2->setGeometry(QRect(1290, 430, 101, 27));
        mMult4 = new QLineEdit(centralWidget);
        mMult4->setObjectName(QStringLiteral("mMult4"));
        mMult4->setGeometry(QRect(1180, 520, 101, 27));
        labelCorrect5 = new QLabel(centralWidget);
        labelCorrect5->setObjectName(QStringLiteral("labelCorrect5"));
        labelCorrect5->setGeometry(QRect(1150, 410, 151, 20));
        labelCorrect5->setFont(font);
        mMult8 = new QLineEdit(centralWidget);
        mMult8->setObjectName(QStringLiteral("mMult8"));
        mMult8->setGeometry(QRect(1290, 550, 101, 27));
        mMult5 = new QLineEdit(centralWidget);
        mMult5->setObjectName(QStringLiteral("mMult5"));
        mMult5->setGeometry(QRect(1290, 520, 101, 27));
        mMult7 = new QLineEdit(centralWidget);
        mMult7->setObjectName(QStringLiteral("mMult7"));
        mMult7->setGeometry(QRect(1180, 550, 101, 27));
        line_h2 = new QFrame(centralWidget);
        line_h2->setObjectName(QStringLiteral("line_h2"));
        line_h2->setGeometry(QRect(430, 400, 281, 20));
        line_h2->setFrameShape(QFrame::HLine);
        line_h2->setFrameShadow(QFrame::Sunken);
        labelCore1 = new QLabel(centralWidget);
        labelCore1->setObjectName(QStringLiteral("labelCore1"));
        labelCore1->setGeometry(QRect(730, 120, 121, 20));
        labelCore1->setFont(font);
        labelCore = new QLabel(centralWidget);
        labelCore->setObjectName(QStringLiteral("labelCore"));
        labelCore->setGeometry(QRect(830, 0, 121, 20));
        labelCore->setFont(font1);
        line_v2 = new QFrame(centralWidget);
        line_v2->setObjectName(QStringLiteral("line_v2"));
        line_v2->setGeometry(QRect(1050, 0, 20, 701));
        line_v2->setFrameShape(QFrame::VLine);
        line_v2->setFrameShadow(QFrame::Sunken);
        labelGyroBias = new QLabel(centralWidget);
        labelGyroBias->setObjectName(QStringLiteral("labelGyroBias"));
        labelGyroBias->setGeometry(QRect(10, 430, 81, 20));
        labelGyroBias->setFont(font);
        labelGyroScale = new QLabel(centralWidget);
        labelGyroScale->setObjectName(QStringLiteral("labelGyroScale"));
        labelGyroScale->setGeometry(QRect(10, 450, 81, 20));
        labelGyroScale->setFont(font);
        labelAcclScale = new QLabel(centralWidget);
        labelAcclScale->setObjectName(QStringLiteral("labelAcclScale"));
        labelAcclScale->setGeometry(QRect(10, 500, 81, 20));
        labelAcclScale->setFont(font);
        labelAcclBias = new QLabel(centralWidget);
        labelAcclBias->setObjectName(QStringLiteral("labelAcclBias"));
        labelAcclBias->setGeometry(QRect(10, 480, 81, 20));
        labelAcclBias->setFont(font);
        labelMagnBias = new QLabel(centralWidget);
        labelMagnBias->setObjectName(QStringLiteral("labelMagnBias"));
        labelMagnBias->setGeometry(QRect(10, 550, 81, 20));
        labelMagnBias->setFont(font);
        labelAcclMag = new QLabel(centralWidget);
        labelAcclMag->setObjectName(QStringLiteral("labelAcclMag"));
        labelAcclMag->setGeometry(QRect(10, 520, 81, 20));
        labelAcclMag->setFont(font);
        labelMagnMag = new QLabel(centralWidget);
        labelMagnMag->setObjectName(QStringLiteral("labelMagnMag"));
        labelMagnMag->setGeometry(QRect(10, 570, 81, 20));
        labelMagnMag->setFont(font);
        labelMagnAng = new QLabel(centralWidget);
        labelMagnAng->setObjectName(QStringLiteral("labelMagnAng"));
        labelMagnAng->setGeometry(QRect(10, 590, 81, 20));
        labelMagnAng->setFont(font);
        textMagnBias = new QLabel(centralWidget);
        textMagnBias->setObjectName(QStringLiteral("textMagnBias"));
        textMagnBias->setGeometry(QRect(90, 550, 191, 20));
        textMagnBias->setFont(font);
        textAcclMag = new QLabel(centralWidget);
        textAcclMag->setObjectName(QStringLiteral("textAcclMag"));
        textAcclMag->setGeometry(QRect(90, 520, 191, 20));
        textAcclMag->setFont(font);
        textGyroScale = new QLabel(centralWidget);
        textGyroScale->setObjectName(QStringLiteral("textGyroScale"));
        textGyroScale->setGeometry(QRect(90, 450, 191, 20));
        textGyroScale->setFont(font);
        textAcclScale = new QLabel(centralWidget);
        textAcclScale->setObjectName(QStringLiteral("textAcclScale"));
        textAcclScale->setGeometry(QRect(90, 500, 191, 20));
        textAcclScale->setFont(font);
        textAcclBias = new QLabel(centralWidget);
        textAcclBias->setObjectName(QStringLiteral("textAcclBias"));
        textAcclBias->setGeometry(QRect(90, 480, 191, 20));
        textAcclBias->setFont(font);
        textMagnMag = new QLabel(centralWidget);
        textMagnMag->setObjectName(QStringLiteral("textMagnMag"));
        textMagnMag->setGeometry(QRect(90, 570, 191, 20));
        textMagnMag->setFont(font);
        textMagnAng = new QLabel(centralWidget);
        textMagnAng->setObjectName(QStringLiteral("textMagnAng"));
        textMagnAng->setGeometry(QRect(90, 590, 191, 20));
        textMagnAng->setFont(font);
        textGyroBias = new QLabel(centralWidget);
        textGyroBias->setObjectName(QStringLiteral("textGyroBias"));
        textGyroBias->setGeometry(QRect(90, 430, 191, 20));
        textGyroBias->setFont(font);
        widget = new GLWidget(centralWidget);
        widget->setObjectName(QStringLiteral("widget"));
        widget->setGeometry(QRect(10, 0, 411, 411));
        labelCorrect = new QLabel(centralWidget);
        labelCorrect->setObjectName(QStringLiteral("labelCorrect"));
        labelCorrect->setGeometry(QRect(1160, 0, 151, 20));
        labelCorrect->setFont(font1);
        calibOpen = new QPushButton(centralWidget);
        calibOpen->setObjectName(QStringLiteral("calibOpen"));
        calibOpen->setGeometry(QRect(1130, 670, 81, 27));
        calibSave = new QPushButton(centralWidget);
        calibSave->setObjectName(QStringLiteral("calibSave"));
        calibSave->setGeometry(QRect(1250, 670, 81, 27));
        noStable = new QCheckBox(centralWidget);
        noStable->setObjectName(QStringLiteral("noStable"));
        noStable->setGeometry(QRect(730, 70, 97, 22));
        noFOM = new QCheckBox(centralWidget);
        noFOM->setObjectName(QStringLiteral("noFOM"));
        noFOM->setGeometry(QRect(840, 70, 97, 22));
        noMove = new QCheckBox(centralWidget);
        noMove->setObjectName(QStringLiteral("noMove"));
        noMove->setGeometry(QRect(940, 70, 97, 22));
        gThreshVal = new QLineEdit(centralWidget);
        gThreshVal->setObjectName(QStringLiteral("gThreshVal"));
        gThreshVal->setGeometry(QRect(730, 140, 151, 27));
        gThreshTime = new QLineEdit(centralWidget);
        gThreshTime->setObjectName(QStringLiteral("gThreshTime"));
        gThreshTime->setGeometry(QRect(900, 140, 151, 27));
        labelCore2 = new QLabel(centralWidget);
        labelCore2->setObjectName(QStringLiteral("labelCore2"));
        labelCore2->setGeometry(QRect(900, 120, 121, 20));
        labelCore2->setFont(font);
        configSave = new QPushButton(centralWidget);
        configSave->setObjectName(QStringLiteral("configSave"));
        configSave->setGeometry(QRect(910, 670, 81, 27));
        configOpen = new QPushButton(centralWidget);
        configOpen->setObjectName(QStringLiteral("configOpen"));
        configOpen->setGeometry(QRect(790, 670, 81, 27));
        dispVectRaw = new QRadioButton(centralWidget);
        dispVectRaw->setObjectName(QStringLiteral("dispVectRaw"));
        dispVectRaw->setGeometry(QRect(430, 200, 81, 22));
        dispVectCor = new QRadioButton(centralWidget);
        dispVectCor->setObjectName(QStringLiteral("dispVectCor"));
        dispVectCor->setGeometry(QRect(510, 200, 111, 22));
        dispVectCor->setChecked(true);
        dispVectFltr = new QRadioButton(centralWidget);
        dispVectFltr->setObjectName(QStringLiteral("dispVectFltr"));
        dispVectFltr->setGeometry(QRect(620, 200, 81, 22));
        labelCore5 = new QLabel(centralWidget);
        labelCore5->setObjectName(QStringLiteral("labelCore5"));
        labelCore5->setGeometry(QRect(960, 190, 91, 20));
        labelCore5->setFont(font);
        aWeight = new QLineEdit(centralWidget);
        aWeight->setObjectName(QStringLiteral("aWeight"));
        aWeight->setGeometry(QRect(730, 210, 101, 27));
        labelCore3 = new QLabel(centralWidget);
        labelCore3->setObjectName(QStringLiteral("labelCore3"));
        labelCore3->setGeometry(QRect(750, 190, 61, 20));
        labelCore3->setFont(font);
        labelCore4 = new QLabel(centralWidget);
        labelCore4->setObjectName(QStringLiteral("labelCore4"));
        labelCore4->setGeometry(QRect(870, 190, 71, 20));
        labelCore4->setFont(font);
        aMagThresh = new QLineEdit(centralWidget);
        aMagThresh->setObjectName(QStringLiteral("aMagThresh"));
        aMagThresh->setGeometry(QRect(950, 210, 101, 27));
        aMag = new QLineEdit(centralWidget);
        aMag->setObjectName(QStringLiteral("aMag"));
        aMag->setGeometry(QRect(840, 210, 101, 27));
        mMag = new QLineEdit(centralWidget);
        mMag->setObjectName(QStringLiteral("mMag"));
        mMag->setGeometry(QRect(840, 280, 101, 27));
        labelCore6 = new QLabel(centralWidget);
        labelCore6->setObjectName(QStringLiteral("labelCore6"));
        labelCore6->setGeometry(QRect(750, 260, 61, 20));
        labelCore6->setFont(font);
        labelCore7 = new QLabel(centralWidget);
        labelCore7->setObjectName(QStringLiteral("labelCore7"));
        labelCore7->setGeometry(QRect(870, 260, 71, 20));
        labelCore7->setFont(font);
        mWeight = new QLineEdit(centralWidget);
        mWeight->setObjectName(QStringLiteral("mWeight"));
        mWeight->setGeometry(QRect(730, 280, 101, 27));
        labelCore8 = new QLabel(centralWidget);
        labelCore8->setObjectName(QStringLiteral("labelCore8"));
        labelCore8->setGeometry(QRect(960, 260, 91, 20));
        labelCore8->setFont(font);
        mMagThresh = new QLineEdit(centralWidget);
        mMagThresh->setObjectName(QStringLiteral("mMagThresh"));
        mMagThresh->setGeometry(QRect(950, 280, 101, 27));
        mAng = new QLineEdit(centralWidget);
        mAng->setObjectName(QStringLiteral("mAng"));
        mAng->setGeometry(QRect(840, 330, 101, 27));
        labelCore9 = new QLabel(centralWidget);
        labelCore9->setObjectName(QStringLiteral("labelCore9"));
        labelCore9->setGeometry(QRect(870, 310, 71, 20));
        labelCore9->setFont(font);
        labelCore10 = new QLabel(centralWidget);
        labelCore10->setObjectName(QStringLiteral("labelCore10"));
        labelCore10->setGeometry(QRect(960, 310, 91, 20));
        labelCore10->setFont(font);
        mAngThresh = new QLineEdit(centralWidget);
        mAngThresh->setObjectName(QStringLiteral("mAngThresh"));
        mAngThresh->setGeometry(QRect(950, 330, 101, 27));
        moveAlpha = new QLineEdit(centralWidget);
        moveAlpha->setObjectName(QStringLiteral("moveAlpha"));
        moveAlpha->setGeometry(QRect(730, 400, 151, 27));
        labelCore11 = new QLabel(centralWidget);
        labelCore11->setObjectName(QStringLiteral("labelCore11"));
        labelCore11->setGeometry(QRect(730, 380, 121, 20));
        labelCore11->setFont(font);
        windowGUI->setCentralWidget(centralWidget);
        menuBar = new QMenuBar(windowGUI);
        menuBar->setObjectName(QStringLiteral("menuBar"));
        menuBar->setGeometry(QRect(0, 0, 1400, 25));
        windowGUI->setMenuBar(menuBar);
        mainToolBar = new QToolBar(windowGUI);
        mainToolBar->setObjectName(QStringLiteral("mainToolBar"));
        windowGUI->addToolBar(Qt::TopToolBarArea, mainToolBar);
        statusBar = new QStatusBar(windowGUI);
        statusBar->setObjectName(QStringLiteral("statusBar"));
        windowGUI->setStatusBar(statusBar);
        toolBar = new QToolBar(windowGUI);
        toolBar->setObjectName(QStringLiteral("toolBar"));
        windowGUI->addToolBar(Qt::TopToolBarArea, toolBar);

        retranslateUi(windowGUI);
        QObject::connect(gBias0, SIGNAL(editingFinished()), windowGUI, SLOT(calib_read()));
        QObject::connect(gBias1, SIGNAL(editingFinished()), windowGUI, SLOT(calib_read()));
        QObject::connect(gBias2, SIGNAL(editingFinished()), windowGUI, SLOT(calib_read()));
        QObject::connect(gMult0, SIGNAL(editingFinished()), windowGUI, SLOT(calib_read()));
        QObject::connect(gMult1, SIGNAL(editingFinished()), windowGUI, SLOT(calib_read()));
        QObject::connect(gMult2, SIGNAL(editingFinished()), windowGUI, SLOT(calib_read()));
        QObject::connect(gMult3, SIGNAL(editingFinished()), windowGUI, SLOT(calib_read()));
        QObject::connect(gMult4, SIGNAL(editingFinished()), windowGUI, SLOT(calib_read()));
        QObject::connect(gMult5, SIGNAL(editingFinished()), windowGUI, SLOT(calib_read()));
        QObject::connect(gMult7, SIGNAL(editingFinished()), windowGUI, SLOT(calib_read()));
        QObject::connect(gMult6, SIGNAL(editingFinished()), windowGUI, SLOT(calib_read()));
        QObject::connect(gMult8, SIGNAL(editingFinished()), windowGUI, SLOT(calib_read()));
        QObject::connect(aBias0, SIGNAL(editingFinished()), windowGUI, SLOT(calib_read()));
        QObject::connect(aBias1, SIGNAL(editingFinished()), windowGUI, SLOT(calib_read()));
        QObject::connect(aBias2, SIGNAL(editingFinished()), windowGUI, SLOT(calib_read()));
        QObject::connect(aMult0, SIGNAL(editingFinished()), windowGUI, SLOT(calib_read()));
        QObject::connect(aMult1, SIGNAL(editingFinished()), windowGUI, SLOT(calib_read()));
        QObject::connect(aMult2, SIGNAL(editingFinished()), windowGUI, SLOT(calib_read()));
        QObject::connect(aMult3, SIGNAL(editingFinished()), windowGUI, SLOT(calib_read()));
        QObject::connect(aMult4, SIGNAL(editingFinished()), windowGUI, SLOT(calib_read()));
        QObject::connect(aMult5, SIGNAL(editingFinished()), windowGUI, SLOT(calib_read()));
        QObject::connect(aMult6, SIGNAL(editingFinished()), windowGUI, SLOT(calib_read()));
        QObject::connect(aMult7, SIGNAL(editingFinished()), windowGUI, SLOT(calib_read()));
        QObject::connect(aMult8, SIGNAL(editingFinished()), windowGUI, SLOT(calib_read()));
        QObject::connect(mBias0, SIGNAL(editingFinished()), windowGUI, SLOT(calib_read()));
        QObject::connect(mBias1, SIGNAL(editingFinished()), windowGUI, SLOT(calib_read()));
        QObject::connect(mBias2, SIGNAL(editingFinished()), windowGUI, SLOT(calib_read()));
        QObject::connect(mMult0, SIGNAL(editingFinished()), windowGUI, SLOT(calib_read()));
        QObject::connect(mMult1, SIGNAL(editingFinished()), windowGUI, SLOT(calib_read()));
        QObject::connect(mMult2, SIGNAL(editingFinished()), windowGUI, SLOT(calib_read()));
        QObject::connect(mMult3, SIGNAL(editingFinished()), windowGUI, SLOT(calib_read()));
        QObject::connect(mMult4, SIGNAL(editingFinished()), windowGUI, SLOT(calib_read()));
        QObject::connect(mMult5, SIGNAL(editingFinished()), windowGUI, SLOT(calib_read()));
        QObject::connect(mMult6, SIGNAL(editingFinished()), windowGUI, SLOT(calib_read()));
        QObject::connect(mMult7, SIGNAL(editingFinished()), windowGUI, SLOT(calib_read()));
        QObject::connect(mMult8, SIGNAL(editingFinished()), windowGUI, SLOT(calib_read()));
        QObject::connect(noGyro, SIGNAL(clicked()), windowGUI, SLOT(config_read()));
        QObject::connect(noAccl, SIGNAL(clicked()), windowGUI, SLOT(config_read()));
        QObject::connect(noMagn, SIGNAL(clicked()), windowGUI, SLOT(config_read()));
        QObject::connect(noStable, SIGNAL(clicked()), windowGUI, SLOT(config_read()));
        QObject::connect(noFOM, SIGNAL(clicked()), windowGUI, SLOT(config_read()));
        QObject::connect(noMove, SIGNAL(clicked()), windowGUI, SLOT(config_read()));
        QObject::connect(gThreshVal, SIGNAL(editingFinished()), windowGUI, SLOT(config_read()));
        QObject::connect(gThreshTime, SIGNAL(editingFinished()), windowGUI, SLOT(config_read()));
        QObject::connect(dispScaleGyro, SIGNAL(editingFinished()), windowGUI, SLOT(glWidget_update()));
        QObject::connect(dispScaleAccl, SIGNAL(editingFinished()), windowGUI, SLOT(glWidget_update()));
        QObject::connect(dispScaleMagn, SIGNAL(editingFinished()), windowGUI, SLOT(glWidget_update()));
        QObject::connect(dispScaleIMU, SIGNAL(editingFinished()), windowGUI, SLOT(glWidget_update()));
        QObject::connect(dispVectCor, SIGNAL(clicked()), windowGUI, SLOT(glWidget_update()));
        QObject::connect(dispVectRaw, SIGNAL(clicked()), windowGUI, SLOT(glWidget_update()));
        QObject::connect(dispVectFltr, SIGNAL(clicked()), windowGUI, SLOT(glWidget_update()));

        QMetaObject::connectSlotsByName(windowGUI);
    } // setupUi

    void retranslateUi(QMainWindow *windowGUI)
    {
        windowGUI->setWindowTitle(QApplication::translate("windowGUI", "Real Time Display Tool", 0));
        dispScaleGyro->setText(QApplication::translate("windowGUI", "1000", 0));
        dispScaleAccl->setText(QApplication::translate("windowGUI", "2500", 0));
        dispScaleMagn->setText(QApplication::translate("windowGUI", "5000", 0));
        dispScaleIMU->setText(QApplication::translate("windowGUI", "1000", 0));
        dispEnableGyro->setText(QApplication::translate("windowGUI", "gyroscope", 0));
        dispEnableAccl->setText(QApplication::translate("windowGUI", "accelerometer", 0));
        dispEnableMagn->setText(QApplication::translate("windowGUI", "magnetometer", 0));
        dispEnableIMU->setText(QApplication::translate("windowGUI", "IMU", 0));
        labelDisplay->setText(QApplication::translate("windowGUI", "Display Options", 0));
        labelControls->setText(QApplication::translate("windowGUI", "IMU Controls", 0));
        noGyro->setText(QApplication::translate("windowGUI", "no gyro", 0));
        noAccl->setText(QApplication::translate("windowGUI", "no accl", 0));
        noMagn->setText(QApplication::translate("windowGUI", "no magn", 0));
        viewUp->setText(QApplication::translate("windowGUI", "up", 0));
        viewSide1->setText(QApplication::translate("windowGUI", "side 1", 0));
        viewSide2->setText(QApplication::translate("windowGUI", "side 2", 0));
        up0->setText(QApplication::translate("windowGUI", "0", 0));
        labelUp->setText(QApplication::translate("windowGUI", "up", 0));
        up1->setText(QApplication::translate("windowGUI", "0", 0));
        up2->setText(QApplication::translate("windowGUI", "1", 0));
        selectReference->setText(QApplication::translate("windowGUI", "set reference", 0));
        selectReset->setText(QApplication::translate("windowGUI", "reset", 0));
        selectDeadRecon->setText(QApplication::translate("windowGUI", "dead recon", 0));
        gBias0->setText(QApplication::translate("windowGUI", "0.0", 0));
        gBias1->setText(QApplication::translate("windowGUI", "0.0", 0));
        gBias2->setText(QApplication::translate("windowGUI", "0.0", 0));
        gMult1->setText(QApplication::translate("windowGUI", "0.0", 0));
        gMult2->setText(QApplication::translate("windowGUI", "0.0", 0));
        gMult0->setText(QApplication::translate("windowGUI", "1.0", 0));
        gMult5->setText(QApplication::translate("windowGUI", "0.0", 0));
        gMult3->setText(QApplication::translate("windowGUI", "0.0", 0));
        gMult4->setText(QApplication::translate("windowGUI", "1.0", 0));
        gMult8->setText(QApplication::translate("windowGUI", "1.0", 0));
        gMult6->setText(QApplication::translate("windowGUI", "0.0", 0));
        gMult7->setText(QApplication::translate("windowGUI", "0.0", 0));
        labelCorrect1->setText(QApplication::translate("windowGUI", "gyroscope biases", 0));
        labelCorrect2->setText(QApplication::translate("windowGUI", "gyroscope transformation matrix", 0));
        aBias1->setText(QApplication::translate("windowGUI", "0.0", 0));
        aMult2->setText(QApplication::translate("windowGUI", "0.0", 0));
        aMult7->setText(QApplication::translate("windowGUI", "0.0", 0));
        aMult1->setText(QApplication::translate("windowGUI", "0.0", 0));
        aMult0->setText(QApplication::translate("windowGUI", "1.0", 0));
        aMult3->setText(QApplication::translate("windowGUI", "0.0", 0));
        labelCorrect4->setText(QApplication::translate("windowGUI", "accelerometer transformation matrix", 0));
        aMult8->setText(QApplication::translate("windowGUI", "1.0", 0));
        aBias2->setText(QApplication::translate("windowGUI", "0.0", 0));
        aBias0->setText(QApplication::translate("windowGUI", "0.0", 0));
        aMult5->setText(QApplication::translate("windowGUI", "0.0", 0));
        aMult6->setText(QApplication::translate("windowGUI", "0.0", 0));
        labelCorrect3->setText(QApplication::translate("windowGUI", "accelerometer biases", 0));
        aMult4->setText(QApplication::translate("windowGUI", "1.0", 0));
        mBias1->setText(QApplication::translate("windowGUI", "0.0", 0));
        mMult3->setText(QApplication::translate("windowGUI", "0.0", 0));
        mMult2->setText(QApplication::translate("windowGUI", "0.0", 0));
        mMult6->setText(QApplication::translate("windowGUI", "0.0", 0));
        mMult1->setText(QApplication::translate("windowGUI", "0.0", 0));
        labelCorrect6->setText(QApplication::translate("windowGUI", "magnetometer transformation matrix", 0));
        mBias0->setText(QApplication::translate("windowGUI", "0.0", 0));
        mMult0->setText(QApplication::translate("windowGUI", "1.0", 0));
        mBias2->setText(QApplication::translate("windowGUI", "0.0", 0));
        mMult4->setText(QApplication::translate("windowGUI", "1.0", 0));
        labelCorrect5->setText(QApplication::translate("windowGUI", "magnetometer biases", 0));
        mMult8->setText(QApplication::translate("windowGUI", "1.0", 0));
        mMult5->setText(QApplication::translate("windowGUI", "0.0", 0));
        mMult7->setText(QApplication::translate("windowGUI", "0.0", 0));
        labelCore1->setText(QApplication::translate("windowGUI", "gThreshVal", 0));
        labelCore->setText(QApplication::translate("windowGUI", "Core Structure", 0));
        labelGyroBias->setText(QApplication::translate("windowGUI", "gyro bias:", 0));
        labelGyroScale->setText(QApplication::translate("windowGUI", "gyro scale:", 0));
        labelAcclScale->setText(QApplication::translate("windowGUI", "accl scale:", 0));
        labelAcclBias->setText(QApplication::translate("windowGUI", "accl bias:", 0));
        labelMagnBias->setText(QApplication::translate("windowGUI", "magn bias:", 0));
        labelAcclMag->setText(QApplication::translate("windowGUI", "accl mag:", 0));
        labelMagnMag->setText(QApplication::translate("windowGUI", "magn mag:", 0));
        labelMagnAng->setText(QApplication::translate("windowGUI", "magn ang:", 0));
        textMagnBias->setText(QApplication::translate("windowGUI", "-", 0));
        textAcclMag->setText(QApplication::translate("windowGUI", "-", 0));
        textGyroScale->setText(QApplication::translate("windowGUI", "-", 0));
        textAcclScale->setText(QApplication::translate("windowGUI", "-", 0));
        textAcclBias->setText(QApplication::translate("windowGUI", "-", 0));
        textMagnMag->setText(QApplication::translate("windowGUI", "-", 0));
        textMagnAng->setText(QApplication::translate("windowGUI", "-", 0));
        textGyroBias->setText(QApplication::translate("windowGUI", "-", 0));
        labelCorrect->setText(QApplication::translate("windowGUI", "Correct Structure", 0));
        calibOpen->setText(QApplication::translate("windowGUI", "Open", 0));
        calibSave->setText(QApplication::translate("windowGUI", "Save", 0));
        noStable->setText(QApplication::translate("windowGUI", "no stable", 0));
        noFOM->setText(QApplication::translate("windowGUI", "no FOM", 0));
        noMove->setText(QApplication::translate("windowGUI", "no move", 0));
        gThreshVal->setText(QApplication::translate("windowGUI", "1.0", 0));
        gThreshTime->setText(QApplication::translate("windowGUI", "1.0", 0));
        labelCore2->setText(QApplication::translate("windowGUI", "gThreshTime", 0));
        configSave->setText(QApplication::translate("windowGUI", "Save", 0));
        configOpen->setText(QApplication::translate("windowGUI", "Open", 0));
        dispVectRaw->setText(QApplication::translate("windowGUI", "Raw", 0));
        dispVectCor->setText(QApplication::translate("windowGUI", "Corrected", 0));
        dispVectFltr->setText(QApplication::translate("windowGUI", "Filtered", 0));
        labelCore5->setText(QApplication::translate("windowGUI", "aMagThresh", 0));
        aWeight->setText(QApplication::translate("windowGUI", "0.0", 0));
        labelCore3->setText(QApplication::translate("windowGUI", "aWeight", 0));
        labelCore4->setText(QApplication::translate("windowGUI", "aMag", 0));
        aMagThresh->setText(QApplication::translate("windowGUI", "0.0", 0));
        aMag->setText(QApplication::translate("windowGUI", "0.0", 0));
        mMag->setText(QApplication::translate("windowGUI", "0.0", 0));
        labelCore6->setText(QApplication::translate("windowGUI", "mWeight", 0));
        labelCore7->setText(QApplication::translate("windowGUI", "mMag", 0));
        mWeight->setText(QApplication::translate("windowGUI", "0.0", 0));
        labelCore8->setText(QApplication::translate("windowGUI", "mMagThresh", 0));
        mMagThresh->setText(QApplication::translate("windowGUI", "0.0", 0));
        mAng->setText(QApplication::translate("windowGUI", "0.0", 0));
        labelCore9->setText(QApplication::translate("windowGUI", "mAng", 0));
        labelCore10->setText(QApplication::translate("windowGUI", "mAngThresh", 0));
        mAngThresh->setText(QApplication::translate("windowGUI", "0.0", 0));
        moveAlpha->setText(QApplication::translate("windowGUI", "1.0", 0));
        labelCore11->setText(QApplication::translate("windowGUI", "moveAlpha", 0));
        toolBar->setWindowTitle(QApplication::translate("windowGUI", "toolBar", 0));
    } // retranslateUi

};

namespace Ui {
    class windowGUI: public Ui_windowGUI {};
} // namespace Ui

QT_END_NAMESPACE

#endif // UI_WINDOWGUI_H
